export default [
  {
    slug: 'no-te-invitaron', titulo: 'No te invitaron al paseo', ambito: 'amistad', principio: 'apatheia', virtud: 'sabiduria', cita: 'enq-5',
    situacion: 'Ves en historias de Instagram que tus amigos del colegio se fueron de paseo el fin de semana a una finca. Nadie te dijo nada. Te duele el pecho y empiezas a recordar otras veces en que te sentiste excluido. Piensas en escribir algo sarcástico en el grupo.',
    depende: ['Preguntar con sencillez, sin reproche', 'No actuar desde el resentimiento', 'Cultivar las amistades que sí te buscan'],
    noDepende: ['A quién invitan otros', 'Las razones que tuvieron', 'Lo que piensan de ti'],
    respuesta: 'Duele sentirse fuera, y es humano. Pero Epicteto diría que el hecho —"fueron sin mí"— es distinto del juicio —"no les importo, siempre me excluyen". Quizá fue algo improvisado, quizá hubo un malentendido, quizá sí se están alejando. No lo sabes. Un mensaje sarcástico te daría alivio un minuto y cerraría puertas. Una pregunta sencilla, días después, abre: "Vi que se fueron a la finca, qué bien. Me hubiera encantado ir; ¿la próxima me avisan?". Si la respuesta confirma que hay distancia, esa información también sirve: puedes invertir tu cariño en quienes te buscan. La amistad no se exige; se cultiva.',
    pregunta: '¿Qué amistad que sí te busca estás descuidando por mirar la que no?',
  },
  {
    slug: 'amigo-que-pide-dinero', titulo: 'Un amigo te pide dinero otra vez', ambito: 'amistad', principio: 'los-indiferentes', virtud: 'justicia', cita: 'sen-ep-2',
    situacion: 'Tu amigo de la universidad te escribe: necesita dinero para el arriendo de este mes. Es la tercera vez este año, y de las veces anteriores solo devolvió una parte. Lo aprecias y sabes que está en un momento difícil, pero tú también tienes gastos y sientes que se está aprovechando.',
    depende: ['Decidir cuánto puedes dar sin resentimiento', 'Decir que no con cariño, si es necesario', 'Ofrecer otro tipo de ayuda'],
    noDepende: ['Su situación económica', 'Que te devuelva', 'Cómo reaccione a tu respuesta'],
    respuesta: 'La generosidad es parte de la justicia estoica; la complacencia que te deja resentido, no. El dinero es un indiferente: sirve o daña según cómo se use. Pregúntate: ¿mi préstamo le está ayudando a salir o a no mirar el problema? Puedes ser generoso y claro a la vez: "Esta vez no puedo prestarte, porque las anteriores todavía están pendientes y me afecta. Pero quiero ayudarte: ¿revisamos juntos tus cuentas o te conecto con alguien que tenga trabajo?". Si decides dar, que sea una cantidad que podrías regalar sin rencor. Una amistad que depende de tu billetera no está sana; una que resiste un "no" dicho con cariño, sí.',
    pregunta: '¿Qué tipo de ayuda le sirve de verdad a tu amigo, más allá del dinero?',
  },
  {
    slug: 'amiga-exitosa', titulo: 'La envidia por el éxito de una amiga', ambito: 'amistad', principio: 'los-indiferentes', virtud: 'templanza', cita: 'med-12-4',
    situacion: 'Tu mejor amiga te cuenta feliz que la aceptaron en una maestría en el exterior con beca completa. Tú aplicaste a la misma convocatoria y no pasaste. La felicitas, pero esa noche no puedes dormir, y al día siguiente contestas sus mensajes con monosílabos. Te avergüenza sentirte así.',
    depende: ['Reconocer la envidia sin castigarte', 'Separar tu frustración de tu amistad', 'Decidir tu siguiente paso'],
    noDepende: ['El resultado de la convocatoria', 'La suerte o el talento de tu amiga', 'La sensación que ya apareció'],
    respuesta: 'La envidia es una pasión que nace de un juicio: "su éxito me hace menos". Pero su beca no te quita nada; tu resultado habría sido igual si ella no hubiera aplicado. Marco Aurelio notaba cuánto pesa la comparación con los demás. Nombrar la envidia ya es sabiduría: no te hace mala amiga; te hace humana. Lo que sí sería injusto es castigarla a ella con tu frialdad. Puedes incluso decírselo: "Estoy feliz por ti y también triste por mí; dame unos días". Y luego pregúntate qué harás tú: aplicar de nuevo, buscar otra ruta. Su éxito puede ser un espejo que te inspira en lugar de uno que te humilla.',
    pregunta: '¿Qué te está mostrando esta envidia sobre lo que deseas?',
  },
  {
    slug: 'chisme', titulo: 'Te enteras de que hablaron mal de ti', ambito: 'amistad', principio: 'apatheia', virtud: 'justicia', cita: 'enq-48',
    situacion: 'Una conocida te cuenta que, en una reunión, un amigo cercano dijo que eras "muy intenso" y que "nadie te aguanta mucho tiempo". Otros se rieron. Te sientes traicionado y humillado, y empiezas a pensar en todo lo que podrías contar de él para devolverle el golpe.',
    depende: ['Verificar antes de concluir', 'Hablar directamente con él', 'No responder con chisme'],
    noDepende: ['Lo que dijo', 'Lo que otros pensaron al oírlo', 'La versión que te llegó'],
    respuesta: 'Primero, recuerda que te llegó de segunda mano; los chismes crecen en cada boca. Segundo, aunque fuera exacto, lo que otro dice de ti es asunto suyo. Epicteto aconsejaba que, si te cuentan que alguien habla mal de ti, respondas: "No conocía mis otros defectos, si no, habría mencionado más". Humor que desarma. Tercero, lo que sí depende de ti: hablar directamente con él, sin testigos. "Me contaron esto; prefiero oírlo de ti". Y lo que no harías nunca: devolver chisme por chisme. Entre las señales de quien progresa, dice Epicteto, está no censurar a nadie. Y quizá, al final, valga preguntarse si hay algo de cierto que merezca atención.',
    pregunta: '¿Qué ganarías respondiendo al chisme con chisme, y qué perderías?',
  },
  {
    slug: 'amistad-que-se-apaga', titulo: 'Una amistad se está apagando', ambito: 'amistad', principio: 'amor-fati', virtud: 'templanza', cita: 'enq-8',
    situacion: 'Tu amigo de infancia ya casi no responde. Antes hablaban todos los días; ahora él tiene hijos, un trabajo absorbente y vive en otra ciudad. Siempre eres tú quien escribe. Sientes nostalgia, algo de rabia, y te preguntas si fuiste importante para él.',
    depende: ['Decirle con sinceridad que lo extrañas', 'Aceptar un nuevo ritmo de amistad', 'Abrirte a nuevos vínculos'],
    noDepende: ['Su tiempo y sus prioridades', 'Las etapas de la vida', 'Que la amistad vuelva a ser como antes'],
    respuesta: 'Las amistades cambian de forma como cambian las estaciones. Epicteto aconseja no pretender que las cosas sucedan como queremos, sino querer que sucedan como suceden. Eso no significa rendirse: puedes escribirle una vez, con honestidad y sin reproche: "Te extraño. Sé que tu vida está a tope; ¿una llamada al mes?". Si acepta, la amistad tendrá un nuevo ritmo, quizá más espaciado pero real. Si no, lo que vivieron sigue siendo verdadero y valioso. Que haya cambiado no significa que no fuiste importante. Mientras tanto, cuida los vínculos del presente. No hay que llorar la estación que pasó para disfrutar la que llega.',
    pregunta: '¿Qué amistad actual merece la atención que le das a la nostalgia?',
  },
  {
    slug: 'decir-verdad-a-un-amigo', titulo: 'Tu amigo va a cometer un error', ambito: 'amistad', principio: 'cosmopolitismo', virtud: 'coraje', cita: 'med-6-54',
    situacion: 'Tu amigo está a punto de invertir todos sus ahorros en un negocio que te parece una estafa: rendimientos garantizados, presión para reclutar a otros, un "mentor" que nadie conoce. Está entusiasmado. Si le dices lo que piensas, puede enojarse contigo. Si te callas, puede perderlo todo.',
    depende: ['Decirle lo que ves, con datos y con cariño', 'Hacerlo una vez, con claridad', 'Respetar su decisión final'],
    noDepende: ['Que te crea', 'Que invierta o no', 'Cómo reaccione a tu opinión'],
    respuesta: 'La amistad estoica no es complacencia. Si ves que un amigo se acerca a un abismo, callar por miedo a su enojo es cobardía disfrazada de respeto. Marco Aurelio recordaba que lo que no sirve a la colmena no sirve a la abeja: tu comodidad no es más importante que su bienestar. Díselo con cariño y datos: "Te quiero y por eso te digo esto: estas señales suelen ser de estafa. ¿Lo revisamos juntos antes de invertir?". Después, suelta. Es un adulto y su decisión no depende de ti. Si se equivoca, estarás ahí sin decir "te lo dije". Eso es coraje y justicia al mismo tiempo.',
    pregunta: '¿Qué verdad incómoda le debes a alguien que quieres?',
  },
  {
    slug: 'amigo-en-duelo', titulo: 'No sabes qué decirle a un amigo en duelo', ambito: 'amistad', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'med-2-1',
    situacion: 'La madre de tu amiga murió hace una semana. Fuiste al velorio, pero desde entonces no has escrito porque no sabes qué decir. Temes decir algo torpe o incomodarla. Cada día que pasa te sientes peor por tu silencio, y más difícil se vuelve escribir.',
    depende: ['Escribir algo sencillo hoy', 'Ofrecer ayuda concreta', 'Estar presente en las semanas siguientes, no solo al principio'],
    noDepende: ['Su dolor', 'El tiempo que le tome el duelo', 'Cómo responda a tu mensaje'],
    respuesta: 'No necesitas palabras perfectas; necesitas estar. Los estoicos creían que hemos nacido para acompañarnos, como las manos se ayudan entre sí. Tu miedo a decir algo torpe es comprensible, pero el silencio pesa más que cualquier torpeza. Escribe hoy algo sencillo: "Pienso en ti y en tu mamá. No sé qué decir, pero estoy aquí. ¿Te llevo comida el jueves?". Evita frases que minimicen, como "está en un lugar mejor" o "todo pasa por algo". Y recuerda que el duelo dura más que el velorio: escribe de nuevo en un mes. Si notas que su dolor la desborda por mucho tiempo, anímala con cariño a buscar apoyo profesional.',
    pregunta: '¿A quién le debes un mensaje que estás posponiendo por no saber qué decir?',
    ayuda: true,
  },
  {
    slug: 'broma-pesada', titulo: 'Una broma en el grupo te molestó', ambito: 'amistad', principio: 'apatheia', virtud: 'templanza', cita: 'med-6-6',
    situacion: 'En el grupo de WhatsApp de amigos alguien comparte un meme sobre tu calvicie. Todos responden con risas. Tú también pones un emoji, pero te quedó un mal sabor. Llevas toda la tarde pensando en una respuesta ingeniosa que ridiculice a quien lo publicó.',
    depende: ['Decidir si esto merece tu tarde', 'Decir en privado que no te gustó, si es un patrón', 'Reírte de verdad si puedes'],
    noDepende: ['El humor de tus amigos', 'Lo que otros encuentren gracioso', 'Que el meme ya exista'],
    respuesta: 'Pregúntate primero qué te molestó exactamente: ¿el meme o sentir que tu cuerpo es tema de burla? Si es una broma aislada entre amigos que se quieren, quizá la mejor respuesta estoica sea reírte de verdad: la calvicie es un indiferente, y reírse de uno mismo es una forma de libertad. Si es un patrón que te hiere, dilo con calma y en privado: "Sé que es en broma, pero ese tema no me gusta". Lo que no conviene es pasar la tarde afilando una venganza. Marco Aurelio: la mejor defensa es no parecerte a quien te ofende. Toda la tarde que dedicas a la respuesta es tarde que el meme te quitó.',
    pregunta: '¿Cuánto tiempo le has dado hoy a algo que duró tres segundos?',
  },
  {
    slug: 'poner-limites-amiga', titulo: 'La amiga que solo habla de sí misma', ambito: 'amistad', principio: 'vivir-segun-la-naturaleza', virtud: 'justicia', cita: 'med-4-24',
    situacion: 'Cada vez que te encuentras con tu amiga, ella habla dos horas de sus problemas, de su ex, de su jefe. Cuando intentas contar algo tuyo, lo conecta enseguida con su historia. Sales agotada. La quieres, pero empiezas a poner excusas para no verla.',
    depende: ['Decirle con cariño lo que necesitas', 'Poner límites de tiempo', 'Elegir con qué frecuencia la ves'],
    noDepende: ['Su manera de ser', 'Que se dé cuenta sola', 'Cómo tome tu comentario'],
    respuesta: 'Evitarla con excusas es una forma de injusticia hacia ambas: ella no sabe qué pasa y tú acumulas cansancio. La amistad justa es recíproca. Puedes decirle, en un buen momento: "Te quiero y me gusta escucharte. A veces siento que no alcanzo a contarte mis cosas; ¿me dejas un turno?". Muchas personas no se dan cuenta hasta que alguien se los dice con cariño. También puedes cuidar tu energía: encuentros más cortos, un plan con actividad en lugar de dos horas de café. Marco Aurelio aconsejaba ocuparse de lo necesario. Una amistad necesaria merece honestidad, no huida.',
    pregunta: '¿Qué conversación honesta salvaría una amistad que estás dejando morir en silencio?',
  },
  {
    slug: 'reencuentro-incomodo', titulo: 'Te encuentras con alguien que te hizo daño', ambito: 'amistad', principio: 'premeditatio-malorum', virtud: 'coraje', cita: 'enq-4',
    situacion: 'El sábado es el cumpleaños de un amigo común y sabes que irá una antigua amiga con quien terminaste mal hace dos años, después de que contara un secreto tuyo. Quieres ir a la fiesta, pero te imaginas la tensión, las miradas, y piensas en inventar una excusa para quedarte en casa.',
    depende: ['Prepararte mentalmente para el encuentro', 'Decidir cómo saludarás', 'Cuánto tiempo te quedas'],
    noDepende: ['Que ella vaya', 'Cómo se comporte', 'Lo que otros sepan de la historia'],
    respuesta: 'Epicteto aconsejaba, antes de ir a los baños públicos, imaginar lo que allí ocurre: empujones, gritos, salpicaduras. Así uno va preparado y no pierde la calma. Haz lo mismo: imagina la fiesta con ella presente. Imagina el momento de cruzarse. Decide desde ahora: un saludo cordial y breve, sin fingir amistad ni hacer escenas. Imagina incluso que ella hace un comentario incómodo, y tu respuesta serena. Al llegar, ya lo habrás vivido, y tendrá menos poder. No dejes que alguien que ya no está en tu vida decida a qué fiestas vas. Tu amigo merece tu presencia.',
    pregunta: '¿Qué momento difícil podrías ensayar en tu mente antes de que llegue?',
  },
];
