export default [
  {
    slug: 'trancon', titulo: 'Atrapado en el trancón', ambito: 'ciudad', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'enq-8',
    situacion: 'Vas en el bus hacia el trabajo y el tráfico no se mueve. Un accidente bloqueó la avenida. Vas a llegar al menos cuarenta minutos tarde a una reunión importante. Miras el reloj cada minuto, resoplas, y sientes que la ciudad entera conspira contra ti.',
    depende: ['Avisar que llegarás tarde', 'Usar el tiempo en algo útil o agradable', 'Cómo llegas a la reunión: tenso o sereno'],
    noDepende: ['El accidente', 'El tráfico', 'La hora a la que llegarás'],
    respuesta: 'Este es el ejercicio estoico por excelencia: una situación que no puedes cambiar ni un milímetro. Mirar el reloj cada minuto no mueve el bus; solo te agota. Epicteto aconseja querer que las cosas sucedan como suceden. Traducido a hoy: el trancón ya es un hecho. Escribe un mensaje breve avisando que llegarás tarde, con una propuesta concreta. Luego tienes un regalo inesperado: cuarenta minutos. Puedes leer, escuchar algo que te guste, llamar a tu mamá o simplemente descansar los ojos. Llegarás tarde de todos modos. Lo único que decides es si llegas agotado por la rabia o sereno.',
    pregunta: '¿Qué harías con tiempo perdido si decidieras que no está perdido?',
  },
  {
    slug: 'robo-celular', titulo: 'Te robaron el celular', ambito: 'ciudad', principio: 'los-indiferentes', virtud: 'coraje', cita: 'enq-11',
    situacion: 'Saliendo del metro, alguien te arrebata el celular y corre entre la gente. Todo pasa en tres segundos. No te hicieron daño físico, pero te sientes violentado, tonto por no haberlo cuidado mejor, y con rabia hacia la ciudad y hacia quien lo hizo.',
    depende: ['Bloquear el equipo y proteger tus cuentas', 'Denunciar', 'Permitirte el susto y hablarlo', 'Aprender medidas de cuidado sin vivir con miedo'],
    noDepende: ['Lo que hizo el ladrón', 'Recuperar el celular', 'La inseguridad de la ciudad'],
    respuesta: 'Lo primero: estás bien. El susto es real y merece atención; cuéntalo a alguien. Luego, lo práctico: bloquea el equipo, cambia contraseñas, denuncia. Epicteto enseñaba a decir de las cosas "las he devuelto": el celular era un objeto, un indiferente, y ahora ya no está. Culparte por no haberlo cuidado más solo añade una segunda herida. La rabia hacia la ciudad es comprensible, pero no te protege; lo que te protege es tomar medidas razonables sin vivir con miedo. Tus fotos quizá estén respaldadas; tu serenidad todavía puedes conservarla. No dejes que un ladrón se lleve también tu confianza en la gente.',
    pregunta: '¿Qué te quitaron realmente, y qué sigue siendo tuyo?',
  },
  {
    slug: 'vecino-ruidoso', titulo: 'El vecino pone música a todo volumen', ambito: 'ciudad', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'med-6-54',
    situacion: 'Es martes, once de la noche, y el vecino de arriba tiene música a todo volumen otra vez. Mañana te levantas a las cinco. Ya has golpeado el techo con la escoba dos veces. Estás pensando en subir a gritarle o en poner tu propia música más fuerte para que "sepa lo que se siente".',
    depende: ['Hablar con él con respeto', 'Acudir a la administración o a las normas de convivencia', 'Buscar soluciones temporales para dormir'],
    noDepende: ['Sus hábitos', 'Su nivel de consideración', 'Que cambie esta noche'],
    respuesta: 'Marco Aurelio decía que lo que no sirve a la colmena no sirve a la abeja: la convivencia es un bien común, y tu vecino está fallando en ella. Pero responder con más ruido solo agranda el daño para todos. Sube, si te sientes seguro, y habla en tono calmado: "Buenas noches, mañana madrugo y la música se escucha mucho en mi apartamento. ¿Podrías bajarle?". Muchas personas no saben cuánto se oye. Si se repite, acude a la administración o a las normas de convivencia; es un camino justo, no una venganza. Mientras tanto, unos tapones para los oídos pueden salvar tu noche.',
    pregunta: '¿Cómo te gustaría que te hablaran si fueras tú quien molesta sin saberlo?',
  },
  {
    slug: 'cola-del-banco', titulo: 'Una fila eterna en el trámite', ambito: 'ciudad', principio: 'apatheia', virtud: 'templanza', cita: 'enq-4',
    situacion: 'Llevas dos horas en una fila para renovar un documento. Solo hay un funcionario atendiendo. Alguien se cuela delante de ti. Cuando por fin llegas a la ventanilla, te dicen que falta una fotocopia y que debes volver otro día. Sientes que vas a explotar.',
    depende: ['Cómo le hablas al funcionario', 'Preguntar exactamente qué necesitas para la próxima vez', 'Decir con calma si alguien se cuela'],
    noDepende: ['La burocracia', 'El número de funcionarios', 'La conducta de quien se coló'],
    respuesta: 'Epicteto aconsejaba, antes de ir a los baños públicos, recordar lo que allí pasa: empujones, ruido, gente que salpica. Así uno va preparado. Las filas de los trámites son nuestros baños públicos. La próxima vez, antes de salir, dite: "Habrá demoras, alguien se colará, quizá falte un papel; y quiero mantener mi serenidad". Hoy, el funcionario no inventó la regla de la fotocopia; gritarle es castigar a quien no tiene la culpa. Pregunta con claridad todo lo que necesitas, anótalo, y vuelve preparado. Si alguien se cuela, puedes decirlo con firmeza y sin rabia. Llegar a casa sereno también es un triunfo.',
    pregunta: '¿Qué situación rutinaria te exaspera y podrías prever antes de salir?',
  },
  {
    slug: 'conductor-agresivo', titulo: 'Un conductor te cierra y te insulta', ambito: 'ciudad', principio: 'apatheia', virtud: 'templanza', cita: 'sen-ira-2-29',
    situacion: 'Vas manejando y un carro te cierra bruscamente. Frenas a tiempo. El otro conductor, además, te pita y te hace un gesto obsceno por la ventana. Sientes una oleada de adrenalina y el impulso de acelerar para alcanzarlo y decirle cuatro cosas.',
    depende: ['Respirar y soltar el acelerador', 'Mantener tu seguridad y la de otros', 'No devolver el gesto'],
    noDepende: ['La forma de manejar de otros', 'Su gesto', 'Su día y sus problemas'],
    respuesta: 'Séneca escribió que el mejor remedio para la ira es la demora. Aquí la demora no es solo sabiduría: es seguridad. Perseguir a otro conductor enfurecido es exponer tu vida por un gesto de tres segundos. La adrenalina es un primer movimiento; no la elegiste. Lo que elijas ahora, sí. Suelta el acelerador, respira profundo tres veces y deja que se aleje. Quizá va tarde a un hospital, quizá tuvo un día terrible, quizá simplemente maneja mal. En cualquier caso, no es tu tarea educarlo. Tu tarea es llegar bien a tu destino. Nadie gana una pelea de tráfico.',
    pregunta: '¿Qué te estás jugando cuando respondes a la agresión de un desconocido?',
  },
  {
    slug: 'lluvia-y-planes', titulo: 'La lluvia arruinó el plan', ambito: 'ciudad', principio: 'amor-fati', virtud: 'sabiduria', cita: 'sen-tranq-13',
    situacion: 'Llevabas semanas planeando un picnic en el parque para el cumpleaños de tu hija. Justo cuando sacan las cosas del carro, empieza un aguacero. Los niños invitados están mojados y aburridos, y tú sientes que todo se arruinó y que tu hija va a recordar un cumpleaños fallido.',
    depende: ['Improvisar un nuevo plan', 'Tu actitud frente a los niños', 'Convertir el imprevisto en parte de la aventura'],
    noDepende: ['La lluvia', 'El pronóstico', 'El plan original'],
    respuesta: 'Séneca aconsejaba emprender todo con una reserva: "si nada lo impide". Hoy la lluvia lo impidió. Pero observa: tu hija va a recordar el cumpleaños sobre todo por cómo reaccionen los adultos. Si ve frustración, recordará frustración. Si ve a su papá riéndose bajo la lluvia y proponiendo un picnic en la sala de la casa, con carpas de sábanas, recordará una aventura. Aceptar el destino no es resignarse a un día triste; es tomar lo que llega y trabajar con ello. La lluvia no arruinó el cumpleaños. Solo cambió el guion.',
    pregunta: '¿Qué imprevisto de hoy podrías convertir en una historia que valga la pena contar?',
  },
  {
    slug: 'persona-en-la-calle', titulo: 'Alguien pide ayuda en el semáforo', ambito: 'ciudad', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'dis-1-9',
    situacion: 'Cada mañana, en el mismo semáforo, una mujer con un niño pide dinero. Tú sueles subir la ventana y mirar al frente, sintiéndote incómodo. Hoy el niño te saluda con la mano. Te quedas pensando todo el día en qué deberías hacer y en la desigualdad que ves a diario.',
    depende: ['Tratarla con dignidad, dando o no dando', 'Informarte sobre organizaciones que ayudan', 'Aportar de forma sostenida a alguna causa'],
    noDepende: ['La desigualdad estructural', 'Su historia', 'Resolver el problema tú solo'],
    respuesta: 'Los estoicos se consideraban ciudadanos del mundo: esa mujer y ese niño son tus conciudadanos. La justicia no te obliga a resolver la pobreza, que no depende de ti, pero sí a no volver invisibles a las personas. Mirarla a los ojos y saludar al niño ya es un acto de dignidad, des o no des dinero. Si quieres hacer más, infórmate sobre organizaciones serias que trabajan con familias en situación de calle y aporta de forma constante, aunque sea poco. Así tu ayuda no depende del impulso de un semáforo. La incomodidad que sientes es buena señal: es tu sentido de justicia pidiendo acción.',
    pregunta: '¿Qué acción concreta y sostenida podrías tomar frente a una injusticia que ves a diario?',
  },
  {
    slug: 'mudanza-ciudad-nueva', titulo: 'Te mudaste a una ciudad donde no conoces a nadie', ambito: 'ciudad', principio: 'amor-fati', virtud: 'coraje', cita: 'sen-ep-28',
    situacion: 'Por trabajo te trasladaron a otra ciudad. Llevas un mes. Vives solo, no conoces a nadie, el clima es distinto y extrañas la comida de tu casa. Los fines de semana los pasas viendo series y pensando que fue un error aceptar el cambio.',
    depende: ['Salir a explorar la ciudad', 'Buscar actividades donde conocer gente', 'Mantener el contacto con los tuyos', 'Darte tiempo para adaptarte'],
    noDepende: ['El clima y las costumbres', 'Que la gente te busque', 'El tiempo que tome sentirte en casa'],
    respuesta: 'Séneca decía que cambiar de cielo no sirve si no cambias de ánimo. Lo contrario también es cierto: tu ánimo puede transformar una ciudad extraña en un hogar. Un mes es poco tiempo; la soledad del comienzo es normal, no una prueba de error. Lo que depende de ti es dar pequeños pasos: un paseo cada fin de semana por un barrio distinto, una clase o un grupo de deporte, saludar a los vecinos, probar la comida local con curiosidad. El coraje aquí no es heroico; es salir de la casa un sábado cuando preferirías quedarte. Dale seis meses antes de juzgar.',
    pregunta: '¿Qué pequeña exploración podrías hacer este fin de semana?',
  },
  {
    slug: 'corte-de-luz', titulo: 'Se fue la luz toda la tarde', ambito: 'ciudad', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'sen-ep-18',
    situacion: 'Un corte de energía deja tu barrio sin luz desde el mediodía. Tenías que entregar un trabajo, se te está descongelando la nevera y el celular tiene quince por ciento de batería. Te pasas la primera hora llamando a la empresa de energía y quejándote en redes.',
    depende: ['Avisar a quien espera tu trabajo', 'Organizar lo que se puede salvar', 'Aprovechar la tarde sin pantallas'],
    noDepende: ['Cuándo vuelve la luz', 'La respuesta de la empresa', 'Lo que se dañe en la nevera'],
    respuesta: 'Séneca recomendaba practicar de vez en cuando vivir con menos para descubrir que no era tan terrible. Hoy la ciudad te ofreció esa práctica sin pedirla. Haz lo que depende de ti: un mensaje avisando del retraso, cerrar bien la nevera, guardar batería para lo esencial. Una llamada para reportar el daño es útil; diez llamadas y quejas en redes solo gastan batería y ánimo. Después, acepta la tarde como es: lee junto a la ventana, conversa con tu familia, cocina lo que se va a dañar, sal a caminar. Muchas personas recuerdan con cariño esas tardes sin luz.',
    pregunta: '¿Qué descubrirías si tuvieras una tarde entera sin pantallas?',
  },
  {
    slug: 'protesta-bloqueo', titulo: 'Una protesta bloquea tu camino a casa', ambito: 'ciudad', principio: 'cosmopolitismo', virtud: 'sabiduria', cita: 'med-6-54',
    situacion: 'Una manifestación bloquea la vía principal y no hay transporte. Tendrás que caminar una hora para llegar a casa. Estás cansado y furioso con los manifestantes, aunque no sabes bien qué están reclamando. Empiezas a escribir un comentario indignado en redes.',
    depende: ['Buscar una ruta alternativa segura', 'Informarte sobre qué reclaman', 'Cuidar tu seguridad'],
    noDepende: ['La protesta', 'Las razones de los manifestantes', 'Cuánto dure el bloqueo'],
    respuesta: 'Antes de escribir el comentario, la sabiduría estoica pide algo sencillo: entender. ¿Qué reclaman? Puede que estés de acuerdo o no, pero la indignación sin información es solo ruido. Marco Aurelio recordaba que lo que daña a la colmena daña a la abeja: una ciudad donde algunos sienten que deben bloquear calles para ser escuchados tiene un problema común, no solo de ellos. Eso no significa que el bloqueo no te afecte ni que no puedas estar en desacuerdo. Significa mirar el conjunto. Por ahora, lo que depende de ti: buscar una ruta segura, avisar a los tuyos y caminar con calma. Quizá la hora de camino te sirva para pensar.',
    pregunta: '¿Qué entenderías si escucharas antes de juzgar?',
  },
];
