export default [
  {
    slug: 'deuda-tarjeta', titulo: 'La deuda de la tarjeta crece', ambito: 'dinero', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'sen-ep-2',
    situacion: 'Abres el extracto de la tarjeta de crédito y la deuda llegó a un monto que no te atreves a decir en voz alta. Fueron compras pequeñas: domicilios, ropa en oferta, suscripciones. Sientes vergüenza y ansiedad. Lo primero que haces es cerrar la aplicación y pedir un domicilio para sentirte mejor.',
    depende: ['Mirar las cifras completas', 'Hacer un plan de pago realista', 'Cortar gastos concretos', 'Pedir asesoría si la necesitas'],
    noDepende: ['Las tasas de interés', 'Lo que ya gastaste', 'La publicidad que te llega'],
    respuesta: 'La vergüenza te empuja a no mirar, y no mirar agranda el problema. Lo primero que depende de ti es abrir de nuevo el extracto y anotar la cifra exacta. Una cifra clara asusta menos que una sombra. Luego, un plan: cuánto puedes pagar al mes, qué gastos cortas y cuándo terminarías. Séneca decía que no es pobre quien tiene poco sino quien desea más. Muchas de esas compras compraban alivio, no cosas. La templanza no es privación triste: es recuperar tu libertad de las pequeñas urgencias. Borra las aplicaciones de domicilios por un mes y observa qué emoción aparece cuando quieres pedir.',
    pregunta: '¿Qué emoción estabas intentando calmar con esas compras?',
  },
  {
    slug: 'vecino-carro-nuevo', titulo: 'El vecino estrenó carro', ambito: 'dinero', principio: 'los-indiferentes', virtud: 'templanza', cita: 'sen-ep-2',
    situacion: 'Tu vecino llega con una camioneta nueva. Tú todavía manejas el carro que compraste usado hace ocho años. Esa noche, sin darte cuenta, estás mirando créditos vehiculares en el celular. Tu carro funciona bien, pero de repente te parece viejo y un poco vergonzoso.',
    depende: ['Preguntarte qué necesitas realmente', 'Decidir tus compras con tus propias razones', 'Agradecer lo que tienes y funciona'],
    noDepende: ['Lo que compran los demás', 'Lo que el vecino piense de tu carro', 'La publicidad'],
    respuesta: 'Hasta ayer tu carro era perfecto. Lo que cambió no fue el carro, sino tu juicio, y ese juicio lo encendió una comparación. Séneca: no es pobre quien tiene poco, sino quien desea más. Un carro nuevo es un indiferente preferible; si lo necesitas y puedes pagarlo, adelante. Pero pregúntate con honestidad: ¿lo quiero porque lo necesito o para no sentirme menos? Si es lo segundo, la deuda te traerá años de pagos por una tranquilidad que durará semanas, hasta la próxima comparación. Mañana, al encender tu carro viejo, prueba a darle las gracias por los ocho años de servicio. Suena ridículo. Funciona.',
    pregunta: '¿Qué deseas tener solo porque otro lo tiene?',
  },
  {
    slug: 'estafa-virtual', titulo: 'Te estafaron por internet', ambito: 'dinero', principio: 'amor-fati', virtud: 'sabiduria', cita: 'enq-11',
    situacion: 'Compraste un celular en una página que parecía confiable. Pagaste por transferencia y el vendedor desapareció. Perdiste el equivalente a un mes de ahorro. Te sientes estúpido, repasas una y otra vez las señales que no viste, y no quieres contárselo a nadie por vergüenza.',
    depende: ['Denunciar ante las autoridades y tu banco', 'Aprender las señales para la próxima', 'Contarlo, para que otros no caigan'],
    noDepende: ['Recuperar el dinero', 'Lo que hizo el estafador', 'El pasado'],
    respuesta: 'Te engañó alguien que se dedica a engañar; eso no te hace estúpido, te hace confiado. Epicteto diría: no digas "lo perdí", di "lo devolví". Suena extraño con un estafador de por medio, pero la idea es soltar lo que ya no puedes cambiar para no perder además tu paz. Luego actúa sobre lo que sí depende de ti: denuncia, avisa al banco, guarda los comprobantes. Anota las señales que aprendiste. Y cuéntalo: tu vergüenza protege al estafador; tu historia protege a otros. El fracaso que se convierte en lección deja de ser solo pérdida. Ese dinero se fue; la sabiduría que ganaste se queda.',
    pregunta: '¿Qué aprendiste que podría proteger a alguien que quieres?',
  },
  {
    slug: 'salario-bajo', titulo: 'Tu sueldo no alcanza', ambito: 'dinero', principio: 'dicotomia-del-control', virtud: 'coraje', cita: 'med-5-20',
    situacion: 'Trabajas tiempo completo y aun así a mitad de mes ya no alcanza. Arriendo, transporte, la cuota del estudio. Ves a otros que parecen vivir sin preocupaciones y sientes que la vida es injusta, que por más que te esfuerces nunca vas a salir de esto.',
    depende: ['Conocer exactamente en qué se va tu dinero', 'Buscar formas de aumentar ingresos o capacitarte', 'Pedir un aumento con argumentos'],
    noDepende: ['La economía del país', 'Los salarios del mercado', 'La suerte con la que otros nacieron'],
    respuesta: 'Es verdad que hay injusticias económicas que no dependen de ti, y el estoicismo no pide negarlas. Pero sí pide no quedarte atrapado en ellas. Marco Aurelio decía que lo que se interpone en el camino se convierte en el camino. Este obstáculo concreto pide acciones concretas: un presupuesto honesto de un mes, una lista de habilidades que podrías vender, una conversación preparada con tu jefe sobre un aumento. Nada de eso es mágico. Pero cada paso es tuyo. Compararte con quien vive sin preocupaciones solo agrega amargura a la escasez. Mira tu siguiente paso, no la montaña entera.',
    pregunta: '¿Cuál es el primer paso pequeño que podrías dar esta semana?',
  },
  {
    slug: 'prestamo-familiar-rechazado', titulo: 'Tu familia te negó un préstamo', ambito: 'dinero', principio: 'apatheia', virtud: 'justicia', cita: 'enq-20',
    situacion: 'Pediste a tus tíos, que tienen una buena situación, un préstamo para empezar un negocio. Te dijeron que no, con excusas vagas. Te duele porque tú los ayudaste cuando lo necesitaron. Sientes que no creen en ti y piensas dejar de ir a las reuniones familiares.',
    depende: ['Aceptar su decisión como un derecho suyo', 'Buscar otras fuentes de financiación', 'No confundir el dinero con el afecto'],
    noDepende: ['Su decisión sobre su dinero', 'Sus razones', 'Lo que opinen de tu negocio'],
    respuesta: 'Ellos tienen derecho a decidir sobre su dinero, igual que tú sobre el tuyo. Epicteto diría que lo que te ofende no es su negativa, sino tu juicio: "no creen en mí", "son ingratos". Puede ser cierto o puede que tengan razones que no dijeron. En todo caso, un préstamo no es una medida de amor. Cortar la relación por esto sería castigar un vínculo por un indiferente. Lo que sí depende de ti es buscar otras rutas: bancos, fondos para emprendedores, empezar más pequeño. Quizá dentro de un tiempo, cuando el negocio funcione, agradezcas haberlo hecho con tus propias fuerzas.',
    pregunta: '¿Estás midiendo el afecto de alguien con dinero?',
  },
  {
    slug: 'compras-impulsivas', titulo: 'El carrito de compras a medianoche', ambito: 'dinero', principio: 'los-indiferentes', virtud: 'templanza', cita: 'sen-ep-18',
    situacion: 'Son las doce de la noche, no puedes dormir, y llevas una hora en una tienda en línea. Ya tienes en el carrito unos audífonos, un organizador de escritorio y dos camisetas. Nada es urgente. Sientes un pequeño cosquilleo de emoción al imaginar que llegan. El dedo está sobre "comprar".',
    depende: ['Esperar veinticuatro horas antes de pagar', 'Cerrar la aplicación y hacer otra cosa', 'Observar la emoción que hay detrás'],
    noDepende: ['Las ofertas y la publicidad', 'El insomnio de esta noche', 'Los algoritmos que te muestran productos'],
    respuesta: 'Séneca proponía reservar días para vivir con poco y preguntarse: "¿era esto lo que temía?". Hoy puedes hacer una versión moderna: deja el carrito lleno y espera veinticuatro horas. Si mañana sigues queriendo esas cosas, cómpralas con tranquilidad. Casi siempre el deseo se desinfla. El cosquilleo que sientes no es por los audífonos; es por la sensación de novedad, que dura lo que tarda en llegar el paquete. La templanza no es negarse todo; es que tus compras las decidas tú y no tu insomnio. Cierra la aplicación, apaga la pantalla y lee algo en papel.',
    pregunta: '¿Qué estás buscando realmente cuando compras sin necesidad?',
  },
  {
    slug: 'negocio-quebro', titulo: 'Tu negocio quebró', ambito: 'dinero', principio: 'amor-fati', virtud: 'coraje', cita: 'sen-prov-5',
    situacion: 'Después de tres años, cierras la cafetería que abriste con tus ahorros y un préstamo. La pandemia primero, luego el arriendo, luego la competencia. Hoy entregaste las llaves. Sientes que fracasaste frente a todos los que dijeron que era mala idea, y no sabes cómo empezar de nuevo.',
    depende: ['Hacer un balance honesto de lo aprendido', 'Organizar las deudas con un plan', 'Darte tiempo para el duelo', 'Decidir el próximo paso sin prisa'],
    noDepende: ['La economía y la competencia', 'Lo que opinen los que "tenían razón"', 'Que el negocio haya cerrado'],
    respuesta: 'Séneca escribió que el fuego prueba el oro y la adversidad prueba a los fuertes. Te atreviste a algo que la mayoría solo imagina, y lo sostuviste tres años en condiciones difíciles. Eso no es fracaso; es experiencia comprada a un precio alto. El negocio era un indiferente; tu coraje, tu trabajo y lo que aprendiste son tuyos. Deja pasar unos días. Luego, siéntate con papel: ¿qué funcionó?, ¿qué no?, ¿qué haría distinto? Organiza las deudas paso a paso. Y en cuanto a los que dijeron que era mala idea: la opinión ajena no es tu brújula. Tu próximo paso puede ser otro negocio o un empleo; ambos son dignos.',
    pregunta: '¿Qué sabes hoy que no sabías hace tres años?',
  },
  {
    slug: 'regalo-caro', titulo: 'No puedes pagar el regalo que esperan', ambito: 'dinero', principio: 'vivir-segun-la-naturaleza', virtud: 'templanza', cita: 'sen-ep-2',
    situacion: 'Se acerca el cumpleaños de tu sobrino y en la familia se acostumbra dar regalos costosos. Este año tus finanzas están apretadas. Te da vergüenza llegar con algo sencillo y estás pensando en endeudarte para no quedar mal frente a tus hermanos.',
    depende: ['Dar según tus posibilidades', 'Hacer un regalo con significado', 'Hablar con honestidad si te preguntan'],
    noDepende: ['Las costumbres de tu familia', 'Lo que opinen del regalo', 'Las expectativas del niño'],
    respuesta: 'Endeudarte para cumplir con una expectativa es entregar tu libertad a la opinión ajena. Séneca diría que no es pobre quien tiene poco sino quien desea aparentar más. Un regalo es una expresión de afecto, y el afecto no se mide en precio. Piensa qué le gusta de verdad a tu sobrino: quizá una tarde juntos, un libro elegido con cuidado, algo hecho por ti. Los niños recuerdan el tiempo compartido más que los objetos. Si alguien comenta, puedes decir con tranquilidad: "Este año decidí regalar distinto". Eso también enseña algo valioso a tu sobrino.',
    pregunta: '¿Qué podrías regalar que cueste poco dinero y mucho cuidado?',
  },
  {
    slug: 'inversion-perdida', titulo: 'Tu inversión perdió valor', ambito: 'dinero', principio: 'premeditatio-malorum', virtud: 'sabiduria', cita: 'sen-tranq-13',
    situacion: 'Hace un año invertiste parte de tus ahorros en acciones siguiendo consejos de un canal de internet. Hoy valen la mitad. Revisas el precio veinte veces al día, no duermes bien y te culpas por no haber vendido antes. Estás pensando en vender todo ahora mismo, en pánico.',
    depende: ['No decidir en pánico', 'Revisar tu estrategia con información seria', 'Invertir en adelante solo lo que puedas perder'],
    noDepende: ['El precio de mañana', 'El mercado', 'Lo que ya pasó'],
    respuesta: 'Séneca recomendaba emprender todo con una reserva: "si nada lo impide". En las inversiones esa reserva es obligatoria: el mercado sube y baja, y quien invierte sin haber aceptado antes la posibilidad de perder, invierte con el estómago. Revisar el precio veinte veces no cambia el precio; solo cambia tu ánimo. No tomes decisiones hoy, en pánico. Busca información seria o asesoría independiente y decide con cabeza fría. Y para el futuro, una regla estoica: invierte solo lo que podrías perder sin perder la paz. El dinero es un indiferente; tu sueño y tu juicio, no.',
    pregunta: '¿Qué decisión tomarías si no hubieras mirado el precio hoy?',
  },
  {
    slug: 'ganancia-inesperada', titulo: 'Recibiste un dinero inesperado', ambito: 'dinero', principio: 'los-indiferentes', virtud: 'justicia', cita: 'enq-11',
    situacion: 'Te llega una prima extraordinaria en el trabajo, equivalente a tres sueldos. Lo primero que piensas es en un viaje y un celular nuevo. También recuerdas que tu madre necesita arreglar el techo y que tienes una deuda pendiente con un amigo. Sientes el impulso de gastarlo todo antes de que "se esfume".',
    depende: ['Decidir el uso del dinero con calma', 'Cumplir tus deudas y deberes', 'Disfrutar una parte sin culpa'],
    noDepende: ['Que vuelva a haber primas', 'Lo que otros esperen de ti', 'La tentación inicial'],
    respuesta: 'La buena fortuna también es un indiferente, y los estoicos la miraban con la misma calma que la mala. Epicteto diría que ese dinero te fue prestado por la fortuna: úsalo bien mientras lo tienes. Usarlo bien no significa no disfrutar nada. Significa ordenarlo: primero la deuda con tu amigo, que es un asunto de justicia; luego el techo de tu madre, que es un deber; luego un ahorro para el futuro; y una parte para algo que disfrutes, sin culpa. Espera una semana antes de gastar. Si en siete días el viaje sigue siendo una ilusión sana, ve con la conciencia tranquila.',
    pregunta: 'Si esta suerte fuera prestada, ¿cómo te gustaría haberla usado?',
  },
];
