export default [
  {
    slug: 'perdiste-el-examen', titulo: 'Perdiste el examen que más estudiaste', ambito: 'estudio', principio: 'dicotomia-del-control', virtud: 'sabiduria', cita: 'dis-2-17',
    situacion: 'Estudiaste dos semanas para el parcial de cálculo. Hoy publicaron las notas: 2,4. Tu compañero, que estudió una noche, sacó 4,0. Sientes que no sirves para esto, que elegiste mal la carrera y que tus papás se van a decepcionar.',
    depende: ['Revisar el examen para entender los errores', 'Pedir asesoría al profesor', 'Ajustar tu forma de estudiar'],
    noDepende: ['La nota que ya salió', 'La facilidad de otros', 'La reacción de tus papás'],
    respuesta: 'Una nota es un dato, no un veredicto sobre tu valor. Lo que depende de ti ahora es convertir ese dato en información: ¿en qué te equivocaste?, ¿fue falta de comprensión o de práctica?, ¿estudiaste leyendo o resolviendo ejercicios? Epicteto decía que nadie aprende lo que cree que ya sabe; tú tienes la ventaja de saber exactamente qué no sabes. Pide la revisión, ve a tutoría, cambia de método. Compararte con tu compañero no te enseña nada; cada uno tiene su ritmo. Y sobre tus papás: su reacción no está en tus manos, pero contarles con honestidad lo que harás para mejorar, sí.',
    pregunta: '¿Qué te enseñó este examen que no sabías antes de presentarlo?',
  },
  {
    slug: 'procrastinacion-tesis', titulo: 'Llevas semanas sin avanzar la tesis', ambito: 'estudio', principio: 'vivir-segun-la-naturaleza', virtud: 'coraje', cita: 'sen-brev-1',
    situacion: 'La entrega del borrador de tesis es en un mes y llevas semanas abriendo el documento, escribiendo una línea y cerrándolo. Revisas redes, limpias el cuarto, reorganizas carpetas. Cada día que pasa te sientes más culpable y el proyecto parece más gigante.',
    depende: ['Dividir el trabajo en pasos pequeños', 'Trabajar veinticinco minutos sin distracciones', 'Pedir retroalimentación temprana'],
    noDepende: ['El tiempo que ya pasó', 'La exigencia de tu director', 'Sentir ganas antes de empezar'],
    respuesta: 'Séneca decía que no tenemos poco tiempo, sino que perdemos mucho. La procrastinación rara vez es pereza; suele ser miedo: a que salga mal, a no estar a la altura. El proyecto entero es demasiado grande para empezar, así que no empieces el proyecto: empieza un párrafo. Pon un temporizador de veinticinco minutos, deja el celular en otra habitación y escribe mal a propósito. Lo que escribas se puede corregir; lo que no escribas, no. No esperes tener ganas: las ganas suelen llegar después de empezar, no antes. Y comparte un borrador imperfecto con tu director; la retroalimentación temprana es más valiosa que la perfección tardía.',
    pregunta: '¿Cuál es el paso más pequeño que podrías hacer en los próximos veinticinco minutos?',
  },
  {
    slug: 'profesor-injusto', titulo: 'El profesor te calificó injustamente', ambito: 'estudio', principio: 'dicotomia-del-control', virtud: 'justicia', cita: 'med-6-6',
    situacion: 'Entregaste un ensayo trabajado y el profesor te puso una nota baja sin comentarios. Un compañero con un trabajo similar sacó mucho más. Estás convencido de que el profesor te tiene fastidio desde que cuestionaste algo en clase. Piensas escribir una queja furiosa en la plataforma de evaluación docente.',
    depende: ['Pedir una revisión con argumentos', 'Hablar con el profesor en persona', 'Seguir los canales formales si es necesario'],
    noDepende: ['Los criterios del profesor', 'Lo que piense de ti', 'La decisión final sobre la nota'],
    respuesta: 'Es posible que haya una injusticia, y la justicia estoica no te pide aceptarla en silencio. Pero sí te pide actuar con justicia tú también. Una queja furiosa desahoga, pero no corrige nada y puede cerrarte puertas. Marco Aurelio: la mejor defensa es no parecerte a quien te ofende. Solicita una revisión y ve a hablar con él con preguntas, no con acusaciones: "¿Qué le faltó a mi trabajo para una mejor nota?". Si su respuesta no tiene fundamento, usa los canales formales, con calma y evidencia. Así, pase lo que pase con la nota, habrás defendido lo justo sin perder tu integridad.',
    pregunta: '¿Cómo defenderías lo justo sin volverte injusto en la forma?',
  },
  {
    slug: 'carrera-equivocada', titulo: 'Crees que elegiste mal la carrera', ambito: 'estudio', principio: 'vivir-segun-la-naturaleza', virtud: 'sabiduria', cita: 'sen-ep-71',
    situacion: 'Estás en cuarto semestre de derecho, la carrera que tu familia esperaba. Cada día te cuesta más ir a clase. Lo que te entusiasma es el diseño, pero cambiar ahora significaría "perder" dos años y decepcionar a tus padres. Sientes que estás atrapado en una vida que no elegiste.',
    depende: ['Explorar de verdad lo que te interesa', 'Hablar honestamente con tu familia', 'Tomar la decisión con información y no solo con miedo'],
    noDepende: ['Las expectativas de tu familia', 'Los dos años ya cursados', 'El futuro de ambas carreras'],
    respuesta: 'Séneca advertía que si uno no sabe hacia qué puerto navega, ningún viento le es favorable. Tu malestar puede ser una brújula. Los dos semestres cursados no están perdidos: aprendiste a argumentar, a leer con rigor, a conocerte. Seguir en un camino solo porque ya caminaste parte de él es un error de razonamiento. Pero tampoco decidas por impulso: toma un curso de diseño, habla con diseñadores, mira cómo es su día a día. Luego habla con tu familia, sin pedir permiso, sino compartiendo tus razones. Sus expectativas no dependen de ti; tu honestidad con ellos y contigo, sí.',
    pregunta: '¿Qué harías si la opinión de otros no pesara en esta decisión?',
  },
  {
    slug: 'trabajo-en-grupo-universidad', titulo: 'Tu grupo quiere copiar un trabajo', ambito: 'estudio', principio: 'vivir-segun-la-naturaleza', virtud: 'justicia', cita: 'med-10-16',
    situacion: 'Faltan dos días para la entrega del proyecto final. Tu grupo propone copiar partes de un trabajo del semestre pasado que encontraron en internet y "arreglarlo un poco". Dicen que todo el mundo lo hace y que el profesor no se va a dar cuenta. Si te niegas, te van a ver como el aburrido del grupo.',
    depende: ['Decir claramente que no participarás en el plagio', 'Proponer un plan realista para terminar a tiempo', 'Asumir más trabajo si es necesario'],
    noDepende: ['Lo que decidan tus compañeros', 'Lo que piensen de ti', 'Si el profesor lo detectaría o no'],
    respuesta: 'Que "todo el mundo lo hace" no convierte algo en justo. Marco Aurelio se exigía dejar de discutir sobre cómo debe ser un hombre bueno y simplemente serlo. Este es uno de esos momentos pequeños que forman el carácter. Puedes decirlo sin sermones: "Yo no me siento bien copiando. Propongo que dividamos lo que falta así, y yo me encargo de esta parte". Ofrecer una solución hace más fácil que te sigan. Si insisten, deja claro que no pondrás tu nombre en algo copiado. Sí, es posible que te llamen aburrido. Es un precio pequeño por dormir con la conciencia en paz.',
    pregunta: '¿Qué tipo de profesional estás empezando a ser con esta decisión?',
  },
  {
    slug: 'hablar-en-clase', titulo: 'Te da miedo preguntar en clase', ambito: 'estudio', principio: 'apatheia', virtud: 'coraje', cita: 'enq-48',
    situacion: 'Llevas tres clases sin entender un tema de física. Quieres levantar la mano, pero temes que tu pregunta sea tonta y que todos se rían. Tu compañero de al lado parece entender todo. Al final no preguntas, y en la casa pasas dos horas tratando de entender lo que el profesor habría explicado en dos minutos.',
    depende: ['Hacer la pregunta', 'Preguntar después de clase o por correo', 'Formar un grupo de estudio'],
    noDepende: ['Lo que piensen tus compañeros', 'Que alguien se ría', 'El ritmo del profesor'],
    respuesta: 'Epicteto describe a quien progresa como alguien que no se preocupa por aparentar que sabe. Tu miedo protege tu imagen y sacrifica tu aprendizaje: un mal negocio. Además, lo más probable es que otros tengan la misma duda y estén esperando que alguien pregunte. La risa de un compañero, si llega, dura segundos; la duda sin resolver te cuesta horas. Si te cuesta mucho, empieza por preguntar después de clase o por correo. Luego, en clase, con una frase sencilla: "Profesor, ¿podría explicar de nuevo este paso?". El coraje también se entrena en cosas pequeñas.',
    pregunta: '¿Cuánto te está costando proteger tu imagen?',
  },
  {
    slug: 'rechazo-universidad', titulo: 'No pasaste a la universidad pública', ambito: 'estudio', principio: 'amor-fati', virtud: 'coraje', cita: 'med-5-20',
    situacion: 'Hoy salieron los resultados del examen de admisión. Te faltaron pocos puntos para medicina en la universidad pública. Tus amigos pasaron. Tu familia no puede pagar una privada. Sientes que todo tu esfuerzo del último año fue en vano y que tu sueño se acabó.',
    depende: ['Darte unos días para procesar', 'Informarte sobre las opciones y la próxima convocatoria', 'Preparar mejor lo que falló'],
    noDepende: ['Los resultados de hoy', 'El número de cupos', 'Los resultados de tus amigos'],
    respuesta: 'Es una frustración grande y merece ser sentida. Pero observa el juicio "mi sueño se acabó": ¿es cierto? Te faltaron pocos puntos; eso habla de lo cerca que estás. Marco Aurelio escribió que el obstáculo se convierte en el camino. Este año puede ser el camino: prepararte mejor, trabajar, estudiar una carrera afín mientras vuelves a presentarte, buscar becas. Muchas personas llegan a su meta por una ruta más larga y llegan más fuertes. El esfuerzo del último año no fue en vano: te dejó hábitos y conocimientos que siguen contigo. Lo que depende de ti ahora es el siguiente paso.',
    pregunta: 'Si este año fuera parte del camino y no un desvío, ¿cómo lo usarías?',
  },
  {
    slug: 'comparacion-con-companeros', titulo: 'Todos parecen más brillantes que tú', ambito: 'estudio', principio: 'los-indiferentes', virtud: 'templanza', cita: 'med-12-4',
    situacion: 'En tu maestría, tus compañeros hablan de publicaciones, congresos y ofertas de trabajo. Tú apenas estás terminando tus lecturas. Sientes que no perteneces allí, que te admitieron por error y que en cualquier momento todos se darán cuenta de que no eres suficiente.',
    depende: ['Enfocarte en tu propio progreso', 'Pedir orientación a tus profesores', 'Compartir tus dudas con compañeros de confianza'],
    noDepende: ['Los logros de los demás', 'Lo que los demás muestran de sí', 'La percepción que otros tengan de ti'],
    respuesta: 'Lo que describes tiene nombre moderno, "síndrome del impostor", y una observación antigua: Marco Aurelio notaba que damos más valor a la opinión ajena que a la propia. Los logros de tus compañeros son indiferentes para tu valor, y además solo ves su vitrina, no sus dudas. Tu único punto de comparación útil es quién eras tú hace seis meses. Te admitieron por una razón; tu tarea es aprender, no aparentar. Habla con un profesor sobre tu ruta. Y cuéntale a un compañero cómo te sientes: te sorprenderá cuántos sienten lo mismo.',
    pregunta: '¿Cómo ha crecido tu conocimiento desde que empezaste, sin compararte con nadie?',
  },
  {
    slug: 'distraccion-celular', titulo: 'No puedes estudiar sin mirar el celular', ambito: 'estudio', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'sen-ep-1',
    situacion: 'Te sientas a estudiar para el examen del viernes. Cada cinco minutos revisas el celular: una notificación, un video, un mensaje. Después de tres horas, apenas has leído diez páginas y sientes que perdiste la tarde. Te frustras contigo y te prometes que mañana será distinto.',
    depende: ['Dónde dejas el celular mientras estudias', 'Desactivar notificaciones', 'Estudiar en bloques con descansos definidos'],
    noDepende: ['Que las aplicaciones estén diseñadas para distraerte', 'Los mensajes que te llegan', 'Las ganas repentinas de revisar'],
    respuesta: 'Séneca comenzaba sus cartas pidiendo a su amigo que reclamara su tiempo, que no dejara que se lo robaran. Hoy los ladrones de tiempo caben en el bolsillo. No controlas el diseño de las aplicaciones ni el impulso de revisar; sí controlas dónde está el celular. No confíes en tu fuerza de voluntad: cambia el entorno. Deja el celular en otra habitación, activa el modo concentración y estudia en bloques de cuarenta minutos con diez de descanso. En el descanso puedes mirarlo sin culpa. La templanza no es luchar todo el tiempo contra la tentación; es no ponerla al alcance de la mano.',
    pregunta: '¿Qué cambio en tu entorno haría innecesaria la fuerza de voluntad?',
  },
  {
    slug: 'beca-perdida', titulo: 'Podrías perder la beca', ambito: 'estudio', principio: 'premeditatio-malorum', virtud: 'coraje', cita: 'sen-ep-13',
    situacion: 'Tu beca exige un promedio mínimo de 3,8 y este semestre vas en 3,6. Si la pierdes, no podrás seguir estudiando. Cada vez que piensas en ello se te cierra el pecho, y la angustia no te deja concentrarte, lo cual empeora tus notas.',
    depende: ['Calcular exactamente qué necesitas en cada materia', 'Hablar con la oficina de becas sobre alternativas', 'Organizar tu estudio de las próximas semanas'],
    noDepende: ['Las reglas de la beca', 'Las notas que ya tienes', 'La dificultad de los exámenes'],
    respuesta: 'Séneca observaba que sufrimos más en la imaginación que en la realidad. Ahora mismo estás sufriendo por una pérdida que todavía no ocurre, y ese sufrimiento está haciendo más probable lo que temes. Hagamos una premeditación útil: imagina con calma que pierdes la beca. ¿Qué harías? Quizá hay recursos, créditos, un semestre de trabajo. Tener un plan B quita poder al miedo. Luego vuelve al plan A: calcula qué nota necesitas en cada materia, habla con la oficina de becas y organiza las próximas semanas. Cada hora de estudio enfocado depende de ti. El resultado final, no.',
    pregunta: '¿Qué harías si lo peor ocurriera? ¿Y qué harás hoy para que no ocurra?',
  },
];
