export default [
  {
    slug: 'critica-de-la-madre', titulo: 'Tu madre critica cómo crías a tus hijos', ambito: 'familia', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'enq-43',
    situacion: 'En el almuerzo del domingo, tu madre comenta frente a todos que tus hijos "están muy consentidos" y que "en sus tiempos eso no pasaba". No es la primera vez. Sientes que te está juzgando como padre y te dan ganas de responderle con lo que ella hizo mal contigo.',
    depende: ['Responder sin herir', 'Decidir cómo crías a tus hijos', 'Hablar con ella en otro momento sobre cómo te afectan esos comentarios'],
    noDepende: ['Las opiniones de tu madre', 'Su forma de expresarse', 'Lo que piensen los demás en la mesa'],
    respuesta: 'Epicteto enseña que toda cosa tiene dos asas. Por una, el comentario es "me está juzgando delante de todos", y esa asa quema. Por la otra, "es mi madre, que se preocupa a su manera y ya no sabe estar sin opinar". No cambias el hecho, cambias por dónde lo tomas. Eso no te obliga a darle la razón: la crianza de tus hijos depende de ti, no de su aprobación. Puedes responder con serenidad: "Gracias, mamá, lo tengo en cuenta", y seguir comiendo. Si el patrón te duele, háblalo después, en privado, con calma: "Cuando lo dices delante de todos me siento desautorizado". Sacar la lista de sus errores solo te haría parecerte a lo que te molesta.',
    pregunta: '¿Por qué asa estás tomando lo que te dicen en tu familia?',
  },
  {
    slug: 'hermano-que-no-paga', titulo: 'Tu hermano no devuelve el préstamo', ambito: 'familia', principio: 'los-indiferentes', virtud: 'justicia', cita: 'enq-43',
    situacion: 'Hace ocho meses le prestaste a tu hermano una suma importante para cubrir una deuda. Prometió pagar en tres meses. No ha devuelto nada y, sin embargo, lo ves publicando fotos de un paseo. Cada vez que hay reunión familiar, evitas hablarle y sientes que la rabia te está envenenando.',
    depende: ['Pedirle una conversación clara sobre el pago', 'Decidir cuánto estás dispuesto a perder', 'No volver a prestar lo que no puedas regalar'],
    noDepende: ['Que te pague', 'Cómo gasta su dinero', 'Lo que otros familiares opinen'],
    respuesta: 'Aquí hay dos asuntos mezclados: el dinero y el vínculo. El dinero es un indiferente; importa, pero no define quién eres. El vínculo con tu hermano, y cómo actúas tú, sí tiene que ver con la virtud. Epicteto, en el pasaje de las dos asas, pone justamente el ejemplo de un hermano injusto: no lo tomes por "es injusto", sino por "es mi hermano". Eso no significa callar. Significa hablar desde el vínculo: "Me afecta que no hayamos hablado del préstamo. ¿Qué puedes pagar y cuándo?". Si no paga, habrás aprendido algo y podrás decidir si das ese dinero por perdido para no perder también a tu hermano. Y en adelante, presta solo lo que podrías regalar sin rencor.',
    pregunta: '¿Qué te importa más recuperar: el dinero o la relación? ¿Puedes intentar ambas cosas?',
  },
  {
    slug: 'padre-enfermo', titulo: 'Tu padre se niega a ir al médico', ambito: 'familia', principio: 'dicotomia-del-control', virtud: 'sabiduria', cita: 'enq-1',
    situacion: 'Tu padre tiene setenta y dos años, tose desde hace semanas y se cansa subiendo escaleras. Le has pedido cinco veces que vaya al médico y siempre responde que "no es nada" y que "los médicos solo buscan enfermedades". Te frustra y te asusta. Anoche discutieron a gritos.',
    depende: ['Expresar tu preocupación con amor y sin ultimátums', 'Pedir ayuda a alguien a quien él escuche', 'Ofrecer acompañarlo y facilitar la cita'],
    noDepende: ['Su decisión final', 'Su salud', 'Sus miedos y creencias sobre los médicos'],
    respuesta: 'Aquí la dicotomía del control duele, porque lo que no depende de ti es justo lo que más te importa. Tu padre es un adulto y su cuerpo, en último término, no está en tus manos. Lo que sí está es la forma en que le hablas. Los gritos nacen del miedo, y el miedo empuja a controlar. Prueba otra entrada: "Papá, no te lo pido porque crea que estás enfermo, sino porque te necesito cerca muchos años. ¿Me acompañas si saco la cita?". Busca a alguien cuya palabra él respete. Y luego, suelta. Habrás hecho tu parte con amor. Si aun así se niega, tu tarea será acompañarlo, no ganarle la discusión.',
    pregunta: '¿Cómo le hablarías si tu objetivo fuera que se sienta querido y no vencido?',
  },
  {
    slug: 'adolescente-portazo', titulo: 'Tu hija adolescente te cierra la puerta', ambito: 'familia', principio: 'apatheia', virtud: 'templanza', cita: 'sen-ira-2-29',
    situacion: 'Le pides a tu hija de quince años que deje el celular para cenar. Te responde "déjame en paz", se levanta y cierra la puerta de su cuarto de un golpe. Sientes que te falta al respeto y que, si no la castigas ya, perderás toda autoridad. Tienes la mano en el picaporte.',
    depende: ['Esperar a que ambos estén calmados', 'Poner una consecuencia justa, dicha con calma', 'Buscar entender qué le pasa'],
    noDepende: ['Las emociones de tu hija', 'Los cambios propios de su edad', 'Que te hable hoy'],
    respuesta: 'Séneca escribió todo un tratado sobre la ira, y su consejo principal cabe en una línea: el mejor remedio para la ira es la demora. Ahora mismo tu juicio es "me está faltando al respeto y debo imponerme ya". Quizá tenga algo de cierto, pero una conversación con la puerta cerrada y ambos alterados solo producirá más portazos. Suelta el picaporte. Dentro de una hora, toca y di: "Lo de antes no estuvo bien, y quiero entender qué te pasa". La consecuencia, si hace falta, se puede poner mañana, igual de firme y sin gritos. Tu autoridad no viene de ganar este minuto, sino de ser alguien estable a quien ella pueda volver.',
    pregunta: '¿Qué decisión tomarías distinto si esperaras una hora antes de actuar?',
  },
  {
    slug: 'navidad-politica', titulo: 'La discusión política en la cena familiar', ambito: 'familia', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'med-6-54',
    situacion: 'En la cena de fin de año, un tío saca el tema de las elecciones. Sus opiniones te parecen injustas y mal informadas. La conversación sube de tono; tu prima llora, alguien golpea la mesa. Sientes el impulso de demostrar que tienes razón con datos y un poco de sarcasmo.',
    depende: ['Decidir si esta es la conversación y el momento', 'Expresar tu desacuerdo sin despreciar', 'Cambiar de tema o retirarte con respeto'],
    noDepende: ['Las opiniones de tu tío', 'Que alguien cambie de parecer esta noche', 'El ambiente que ya se creó'],
    respuesta: 'Tener razón es un indiferente; la armonía de esta mesa, y tu forma de tratar a tu tío, no lo son. Marco Aurelio decía que lo que no sirve a la colmena tampoco sirve a la abeja. ¿A quién le sirve ganar esta discusión esta noche? Probablemente ni siquiera a la causa que defiendes: nadie cambia de opinión mientras se siente humillado. Puedes decir con serenidad: "Pienso muy distinto, tío, y me encantaría hablarlo un día con calma. Hoy quisiera que disfrutemos la cena". El sarcasmo da placer un segundo y deja heridas un año. Defender lo justo no exige ganar cada batalla; exige no perder la justicia en la forma.',
    pregunta: '¿Qué pierdes si esta noche no tienes la última palabra?',
  },
  {
    slug: 'cuidar-a-la-abuela', titulo: 'Eres quien cuida a la abuela', ambito: 'familia', principio: 'vivir-segun-la-naturaleza', virtud: 'justicia', cita: 'med-2-1',
    situacion: 'Desde hace un año tu abuela vive contigo y tú te encargas de sus medicinas, sus citas y sus noches difíciles. Tus hermanos llaman de vez en cuando, envían algo de dinero y dicen que "no tienen tiempo". Estás agotada y resentida, y a veces pierdes la paciencia con ella, lo cual te hace sentir peor.',
    depende: ['Pedir a tus hermanos tareas concretas, no ayuda general', 'Buscar apoyo externo o grupos de cuidadores', 'Reservar un tiempo propio cada semana'],
    noDepende: ['Lo que tus hermanos decidan hacer', 'El avance de la edad de tu abuela', 'Su estado de ánimo cada día'],
    respuesta: 'Cuidar a quien nos cuidó es de lo más profundamente humano que existe; los estoicos lo verían como un deber justo y noble. Pero la justicia también vale para ti: no es justo que cargues sola con todo, y tampoco es sostenible. Marco Aurelio recordaba que nacimos para colaborar, como las manos. Dile a tus hermanos algo concreto: "Necesito que uno venga los sábados y que otro acompañe las citas del mes". Si se niegan, busca otros apoyos. La templanza te pide descansar sin culpa: una cuidadora agotada cuida peor. Y cuando pierdas la paciencia, pide perdón y sigue. No eres una santa; eres una persona haciendo algo difícil y valioso.',
    pregunta: '¿Qué ayuda concreta podrías pedir hoy, con nombre y fecha?',
  },
  {
    slug: 'comparar-hijos', titulo: 'Comparan a tu hijo con su primo', ambito: 'familia', principio: 'los-indiferentes', virtud: 'sabiduria', cita: 'med-12-4',
    situacion: 'Tu cuñada cuenta orgullosa que su hijo ganó una beca y habla tres idiomas. Alguien pregunta cómo va el tuyo en el colegio, y tú respondes con vaguedades. Tu hijo, que tiene dificultades con matemáticas pero es amable y creativo, escucha todo. En el carro de regreso le preguntas, con tono seco, por qué no estudia más.',
    depende: ['Cómo miras a tu hijo', 'Qué valores celebras en voz alta', 'Reparar la conversación del carro'],
    noDepende: ['Los logros de tu sobrino', 'Lo que tu familia valore', 'El ritmo de aprendizaje de tu hijo'],
    respuesta: 'Tu tono en el carro no era por tu hijo; era por tu vergüenza frente a la familia. Marco Aurelio se asombraba de cuánto nos pesa la opinión de otros. Las becas y los idiomas son indiferentes preferibles; bienvenidos si llegan. La amabilidad y la creatividad de tu hijo están mucho más cerca de lo que los estoicos llamaban virtud. Tu hijo necesita saber que lo ves. Mañana puedes decirle: "Ayer te hablé mal por algo que no era tuyo. Me encanta cómo tratas a la gente; y con matemáticas te ayudo". Eso le enseñará más de carácter que cualquier comparación.',
    pregunta: '¿Qué virtud de alguien cercano no estás celebrando porque no aparece en un diploma?',
  },
  {
    slug: 'mudanza-de-los-hijos', titulo: 'Tu hijo se va a vivir a otro país', ambito: 'familia', principio: 'amor-fati', virtud: 'templanza', cita: 'enq-11',
    situacion: 'Tu único hijo consiguió un trabajo en otro continente y viaja en tres semanas. Estás orgullosa y, al mismo tiempo, sientes que te arrancan algo. Pasas las noches pensando que ya no será igual, que lo verás una vez al año, que te quedarás sola, y te cuesta alegrarte con él.',
    depende: ['Disfrutar estas tres semanas', 'Acordar formas de mantener el contacto', 'Construir tu propia vida con proyectos y vínculos'],
    noDepende: ['Su decisión y su camino', 'La distancia', 'Cómo cambiará la relación con el tiempo'],
    respuesta: 'Epicteto tiene una frase dura y liberadora: no digas "lo he perdido", sino "lo he devuelto". Tu hijo nunca fue tuyo; fue confiado a ti para que un día pudiera irse. Que se vaya bien es, en cierto modo, tu obra cumplida. La tristeza es natural y no hay que expulsarla. Pero fíjate cómo el miedo al futuro te está robando el presente: estas tres semanas también son él. Aceptar que se va te permite estar con él de verdad. Luego, la templanza: no conviertas su partida en el centro de tu vida. Retoma algo propio, un curso, una amistad, un proyecto. Él también necesita saber que estás bien.',
    pregunta: '¿Qué harías estas tres semanas si aceptaras del todo que se va?',
  },
  {
    slug: 'suegro-imprudente', titulo: 'Tu suegro hace comentarios hirientes', ambito: 'familia', principio: 'apatheia', virtud: 'coraje', cita: 'enq-20',
    situacion: 'Cada vez que visitas a la familia de tu pareja, tu suegro hace bromas sobre tu peso o sobre tu trabajo "que no da para mucho". Todos se ríen. Tu pareja dice que "él es así". Tú sonríes para no pelear, pero pasas días repasando lo que te dijo y evitas las visitas.',
    depende: ['Decirle con calma que esos comentarios no te gustan', 'Hablar con tu pareja sobre lo que necesitas de ella', 'Decidir cuánto tiempo pasas allí'],
    noDepende: ['El carácter de tu suegro', 'Que los demás se rían', 'Que cambie su manera de ser'],
    respuesta: 'Epicteto: no te ofende quien te insulta, sino tu juicio de que eso te ofende. Esto no significa que lo que dice tu suegro esté bien; significa que su opinión sobre tu cuerpo o tu trabajo no tiene poder sobre tu valor, a menos que tú se lo des. Hay dos tareas. Una interior: dejar de repasar sus frases, porque cada repaso es una segunda herida que te haces tú. Otra exterior, que pide coraje: decirle, sin drama, "No me gustan esas bromas, prefiero que no las hagas". Y pedirle a tu pareja apoyo concreto. Si él sigue, eso habla de él. Tú habrás actuado con dignidad.',
    pregunta: '¿Cuántas veces has repetido tú mentalmente lo que otro dijo una sola vez?',
  },
  {
    slug: 'herencia', titulo: 'La herencia divide a los hermanos', ambito: 'familia', principio: 'los-indiferentes', virtud: 'justicia', cita: 'sen-ep-2',
    situacion: 'Tras la muerte de tu madre, la casa familiar debe repartirse. Uno de tus hermanos quiere venderla ya; otra quiere quedarse viviendo allí; tú sientes que te corresponde más porque la cuidaste los últimos años. Las conversaciones terminan en gritos y reproches de hace treinta años.',
    depende: ['Proponer un mediador o asesoría legal', 'Distinguir lo justo de lo que te dicta el resentimiento', 'Cuidar tu duelo aparte del trámite'],
    noDepende: ['Lo que tus hermanos sientan o exijan', 'Las leyes de sucesión', 'Los recuerdos que cada uno tiene de su madre'],
    respuesta: 'Una casa es un indiferente: se puede usar bien o mal. Una familia, y la justicia entre hermanos, pesan más. Séneca decía que no es pobre quien tiene poco, sino quien desea más; en las herencias el deseo suele disfrazarse de "lo que me corresponde". Pregúntate con honestidad: ¿estoy pidiendo lo justo o estoy cobrando heridas antiguas? Tus años de cuidado merecen reconocimiento, y puedes plantearlo con claridad, mejor con un mediador. Pero separa el duelo del trámite: estás triste por tu madre, no por los metros cuadrados. Llora a tu madre por un lado y negocia la casa por otro, con la cabeza fría. Y si la tristeza te pesa demasiado, un acompañamiento profesional en el duelo puede ayudarte.',
    pregunta: 'Dentro de diez años, ¿qué te gustaría haber conservado: la casa o a tus hermanos?',
    ayuda: true,
  },
];
