export default [
  {
    slug: 'mensaje-en-visto', titulo: 'Te dejó en visto', ambito: 'pareja', principio: 'apatheia', virtud: 'sabiduria', cita: 'enq-5',
    situacion: 'Le escribiste a la persona con la que estás saliendo a las once de la mañana. Son las cuatro de la tarde. El mensaje aparece como leído y no hay respuesta. Ya revisaste su última conexión cuatro veces, redactaste y borraste dos mensajes, y te convenciste de que perdió el interés.',
    depende: ['Qué historia te cuentas sobre el silencio', 'Dejar el celular y seguir con tu día', 'Decir con claridad lo que necesitas, si es un patrón'],
    noDepende: ['Cuándo responde la otra persona', 'Lo que está haciendo ahora', 'Lo que siente por ti'],
    respuesta: 'Hay un hecho, "no ha respondido en cinco horas", y una historia, "ya no le intereso". Epicteto diría que lo que te perturba es la historia. Puede estar en una reunión, cansada, o simplemente ser alguien que responde tarde. No lo sabes. Lo que sí sabes es que revisar su conexión no cambia nada y te quita la tarde. Deja el celular en otra habitación una hora y haz algo que te importe. Si con el tiempo el silencio se vuelve un patrón que te hace mal, eso merece una conversación clara, no una adivinanza. Tu tranquilidad no puede depender de la velocidad con que otro escribe.',
    pregunta: '¿Qué harías con esta tarde si confiaras en que la respuesta llegará cuando tenga que llegar?',
  },
  {
    slug: 'ruptura', titulo: 'Tu pareja terminó la relación', ambito: 'pareja', principio: 'amor-fati', virtud: 'coraje', cita: 'enq-11',
    situacion: 'Después de cuatro años, tu pareja te dice que ya no está enamorada y que prefiere terminar. No hay otra persona ni una pelea concreta: simplemente se acabó para ella. Tú no lo viste venir. Pasas los días releyendo conversaciones viejas buscando en qué momento fallaste y cómo podrías convencerla de volver.',
    depende: ['Permitirte el duelo', 'Dejar de buscar pruebas en el pasado', 'Apoyarte en tus amigos y tu rutina', 'Respetar su decisión'],
    noDepende: ['Lo que ella siente', 'Su decisión', 'Que la historia hubiera sido distinta'],
    respuesta: 'El dolor de una ruptura es real y los estoicos no te pedirían que lo niegues. Pero sí te ayudarían a no multiplicarlo. Releer conversaciones buscando el error es discutir con algo que ya ocurrió. Epicteto propone decir "lo he devuelto" en lugar de "lo he perdido": esos cuatro años fueron un préstamo, y lo que viviste en ellos no se borra. Respetar su decisión es también un acto de justicia: ella tiene derecho a elegir su vida, igual que tú. Tu tarea ahora es cuidar lo que depende de ti: comer, dormir, ver amigos, moverte. Si la tristeza te paraliza por semanas, pide ayuda. Aceptar que terminó es el primer paso para volver a ti.',
    pregunta: '¿Qué te llevas de esta relación que quieres conservar para tu vida?',
  },
  {
    slug: 'celos', titulo: 'Los celos por un compañero de trabajo', ambito: 'pareja', principio: 'apatheia', virtud: 'templanza', cita: 'sen-ira-2-3',
    situacion: 'Tu pareja menciona varias veces a un compañero nuevo: que es muy divertido, que almorzaron juntos, que le ayudó con un proyecto. No ha hecho nada fuera de lugar, pero sientes un nudo en el estómago cada vez que lo nombra, y te descubres revisando su perfil en redes a medianoche.',
    depende: ['Reconocer el celo como un primer movimiento', 'Examinar el juicio que lo alimenta', 'Hablar desde lo que sientes, sin acusar'],
    noDepende: ['Con quién se relaciona tu pareja en su trabajo', 'Lo que siente ella', 'El futuro de la relación'],
    respuesta: 'Séneca distingue el primer movimiento, que no eliges, del asentimiento, que sí. El nudo en el estómago llegó solo. Pero revisar perfiles a medianoche es ya haber dado por cierto un juicio: "me va a dejar por él". ¿Hay pruebas? Por ahora, un compañero amable y una pareja que te lo cuenta con naturalidad, lo cual suele ser buena señal. Puedes decirle con honestidad: "Me doy cuenta de que me dan celos cuando lo nombras; sé que es mío, pero quería contártelo". Eso abre una conversación; espiar la cierra. No controlas su corazón. Sí controlas ser alguien con quien dan ganas de quedarse.',
    pregunta: '¿Qué evidencia real tienes, y qué parte es miedo?',
  },
  {
    slug: 'discusion-repetida', titulo: 'La misma discusión de siempre', ambito: 'pareja', principio: 'dicotomia-del-control', virtud: 'sabiduria', cita: 'enq-43',
    situacion: 'Otra vez discuten por las tareas de la casa. Tú sientes que haces más; tu pareja dice que no valoras lo que hace. En diez minutos pasan de los platos sucios a reproches de hace años. Ambos terminan en cuartos separados, cansados de una pelea que se repite casi igual cada mes.',
    depende: ['Proponer hablarlo en un momento tranquilo', 'Escuchar su versión sin preparar la réplica', 'Proponer un acuerdo concreto y escrito'],
    noDepende: ['Cómo percibe tu pareja las cosas', 'Que acepte tu propuesta', 'Que la discusión no vuelva a aparecer'],
    respuesta: 'Cuando una discusión se repite igual, no es sobre los platos. Epicteto sugiere tomar las cosas por el asa correcta: no "es injusta conmigo" sino "es la persona con quien elegí vivir y ambos estamos cansados". No puedes controlar cómo ve ella las cosas, pero sí cambiar tu parte de la coreografía. La próxima vez que empiece la pelea, prueba decir: "Paremos. Esto nos pasa siempre. ¿Lo hablamos el sábado con un café y hacemos una lista de quién hace qué?". En esa conversación, escucha primero hasta que ella sienta que la entendiste. Un acuerdo escrito no es romántico, pero salva más relaciones que muchas flores.',
    pregunta: '¿Qué parte de la coreografía de esta pelea podrías cambiar tú?',
  },
  {
    slug: 'olvido-aniversario', titulo: 'Olvidó el aniversario', ambito: 'pareja', principio: 'los-indiferentes', virtud: 'justicia', cita: 'med-8-47',
    situacion: 'Hoy cumplen cinco años juntos. Preparaste una cena y un regalo. Tu pareja llega tarde, cansada, y no menciona la fecha. Cuando le muestras la mesa, se da cuenta, se disculpa avergonzado y dice que ha tenido una semana terrible. Tú sientes que no le importas lo suficiente.',
    depende: ['Decir cómo te sientes sin castigar', 'Escuchar su contexto', 'Decidir si disfrutan la cena de todos modos'],
    noDepende: ['Que lo haya olvidado', 'La semana que tuvo', 'Su memoria para las fechas'],
    respuesta: 'La fecha es simbólica, y los símbolos importan; tu desilusión es legítima. Pero Marco Aurelio recuerda que lo que te aflige no es el hecho externo sino tu juicio sobre él, y ese juicio —"no le importo"— puede revisarse con los demás hechos: cinco años, su disculpa sincera, su semana difícil. ¿Un olvido anula todo eso? Puedes decir: "Me dolió, porque para mí este día significa mucho". Y luego elegir: castigar la noche entera o sentarse juntos a cenar lo que preparaste. Lo segundo no es rendirse; es elegir la relación por encima de la ceremonia.',
    pregunta: '¿Qué pesa más en tu balanza: este olvido o los cinco años?',
  },
  {
    slug: 'diferencias-de-dinero', titulo: 'Tu pareja gasta más de lo que acordaron', ambito: 'pareja', principio: 'los-indiferentes', virtud: 'templanza', cita: 'sen-ep-2',
    situacion: 'Acordaron ahorrar para un viaje. Revisando el extracto, descubres que tu pareja hizo varias compras en línea que suman casi un tercio de lo ahorrado este mes. Cuando le preguntas, se pone a la defensiva: "también es mi plata, ¿o ahora me vas a controlar?". Tú te sientes traicionado.',
    depende: ['Hablar del acuerdo, no de su carácter', 'Proponer reglas claras que respeten la autonomía de ambos', 'Revisar tus propios hábitos con la misma lupa'],
    noDepende: ['Sus impulsos de compra', 'Lo que ya gastó', 'Que acepte tu punto de vista'],
    respuesta: 'El dinero es un indiferente, pero los acuerdos entre dos personas tocan la justicia y la confianza. Por eso conviene separar ambas cosas. Si le reprochas "eres irresponsable", atacas su carácter y se defenderá. Si dices "acordamos algo y no se cumplió; ¿qué pasó y cómo lo ajustamos?", hablas del acuerdo. Séneca decía que no es pobre quien tiene poco sino quien desea más; tal vez valga preguntarse juntos qué deseo hay detrás de esas compras: cansancio, ansiedad, recompensa. Propón un modelo claro: una cuenta común para metas y un monto libre para cada uno, sin rendir cuentas. Y revisa tus propios gastos con la misma honestidad.',
    pregunta: '¿Estás defendiendo el acuerdo o tu necesidad de tener la razón?',
  },
  {
    slug: 'infidelidad-descubierta', titulo: 'Descubres una infidelidad', ambito: 'pareja', principio: 'apatheia', virtud: 'coraje', cita: 'med-4-7',
    situacion: 'Por un mensaje que apareció en la pantalla del celular de tu pareja, descubres que lleva meses viéndose con otra persona. Cuando lo confrontas, lo admite. Sientes que el piso se abre, que todo fue mentira, que eres ridículo por no haberlo visto. No sabes si quieres gritar, llorar o irte.',
    depende: ['Darte tiempo antes de decisiones definitivas', 'Buscar apoyo en personas de confianza o en un profesional', 'Decidir, con calma, qué límites necesitas'],
    noDepende: ['Lo que tu pareja hizo', 'Sus razones', 'El pasado que ya ocurrió'],
    respuesta: 'Esto es una herida real, y el estoicismo no la minimiza. Hubo una injusticia hacia ti. Pero Marco Aurelio ofrece una distinción que protege: suprime el juicio "me han dañado" y queda suprimido el daño. No se trata de negar el dolor, sino de no añadir el segundo golpe: "soy ridículo", "no valgo nada". La traición habla de quien traicionó, no de tu valor. No tomes hoy decisiones irreversibles; tu mente está en tormenta. Apóyate en alguien de confianza, y si el dolor te desborda, busca un profesional. Después, con más calma, podrás decidir si hay algo que reconstruir o si lo justo contigo es irte. Ambas opciones pueden ser dignas.',
    pregunta: '¿Qué necesitas hoy para cuidarte, antes de decidir cualquier cosa sobre la relación?',
    ayuda: true,
  },
  {
    slug: 'soledad-soltero', titulo: 'Todos tienen pareja menos tú', ambito: 'pareja', principio: 'los-indiferentes', virtud: 'sabiduria', cita: 'sen-ep-28',
    situacion: 'En el matrimonio de tu mejor amiga eres la única de la mesa sin pareja. Tu tía pregunta en voz alta "¿y tú para cuándo?". Durante la fiesta ves bailar a todas las parejas y te invade la sensación de que algo está mal contigo, de que te estás quedando atrás en una carrera.',
    depende: ['Responder con humor o con serenidad', 'Construir una vida que disfrutes ahora', 'Abrirte a conocer gente sin desesperación'],
    noDepende: ['Las preguntas de tu familia', 'Cuándo aparece alguien', 'Los tiempos de los demás'],
    respuesta: 'Tener pareja es un indiferente preferible: es natural desearlo. Pero no es una carrera, y no define si tu vida es buena. Séneca advertía que viajar no sirve si te llevas contigo a ti mismo: tampoco una pareja resuelve un vacío que no hayas mirado. La pregunta útil no es "¿por qué yo no?" sino "¿estoy viviendo bien hoy?". Cultiva amistades, proyectos, una salud que te guste. Eso no es un consuelo mientras llega alguien; es la vida misma. A tu tía puedes responderle, con una sonrisa: "Cuando sea bueno, tía". Y luego salir a bailar, que la pista no es solo para parejas.',
    pregunta: '¿Qué harías distinto este mes si dejaras de sentir que vas tarde?',
  },
  {
    slug: 'pareja-deprimida', titulo: 'Tu pareja está deprimida', ambito: 'pareja', principio: 'dicotomia-del-control', virtud: 'justicia', cita: 'enq-1',
    situacion: 'Desde hace meses tu pareja duerme mucho, perdió interés en todo y apenas habla. Tú has intentado animarla con planes, regalos y consejos, y nada funciona. Te sientes impotente, cansado, y a veces enojado con ella, lo que te hace sentir culpable.',
    depende: ['Acompañar sin intentar arreglar', 'Animarla a buscar atención profesional y facilitarla', 'Cuidar tu propia salud y tus apoyos'],
    noDepende: ['Su estado de ánimo', 'El tiempo que tome su recuperación', 'Que acepte tu ayuda hoy'],
    respuesta: 'La depresión es una enfermedad, no una falta de ganas ni un problema que se arregla con buenos consejos. Ahí está el primer alivio estoico: no depende de ti curarla. Lo que depende de ti es acompañar con paciencia, y ayudar a que reciba atención profesional: buscar la cita, ofrecerte a ir con ella. Eso es justicia y amor, no fracaso. Tu enojo no te hace mala persona; es el cansancio de quien intenta controlar lo que no puede. Cuídate también: duerme, habla con alguien, pide relevos. Si en algún momento notas señales de que piensa en hacerse daño, busca ayuda de inmediato. No estás solo en esto, y no tienes que estarlo.',
    pregunta: '¿Qué forma de acompañar te sostiene a ti también en el tiempo?',
    ayuda: true,
  },
  {
    slug: 'proyecto-de-vida-distinto', titulo: 'Quieren cosas distintas', ambito: 'pareja', principio: 'vivir-segun-la-naturaleza', virtud: 'coraje', cita: 'sen-ep-71',
    situacion: 'Llevan tres años juntos y se quieren. Pero tú quieres tener hijos y tu pareja está segura de que no. Durante meses evitaron el tema, esperando que alguno cambiara. Hoy, en una conversación sincera, confirman que ninguno de los dos va a cambiar de opinión.',
    depende: ['Ser honesto contigo sobre lo que quieres', 'Tomar una decisión sin culpar al otro', 'Cuidar la forma en que se despiden, si se despiden'],
    noDepende: ['Lo que tu pareja desea para su vida', 'Que el amor alcance para resolverlo', 'El dolor que trae cualquier decisión'],
    respuesta: 'Séneca escribió que si uno no sabe hacia qué puerto navega, ningún viento le es favorable. Ustedes se quieren, y a la vez navegan hacia puertos distintos. Ninguno está equivocado: es justo que cada uno quiera su vida. Seguir juntos esperando que el otro ceda produciría resentimiento a largo plazo. Tomar una decisión honesta pide coraje, porque duele hoy para no dañar mañana. Si deciden separarse, pueden hacerlo con gratitud: esos años fueron buenos y no quedan anulados. Si deciden seguir, que sea con claridad y no con una esperanza escondida. En ambos casos, lo que te pertenece es actuar con verdad.',
    pregunta: '¿Qué estás evitando decidir por miedo al dolor de la decisión?',
  },
];
