export default [
  {
    slug: 'comentario-de-odio', titulo: 'Un desconocido te insulta en redes', ambito: 'redes', principio: 'apatheia', virtud: 'templanza', cita: 'enq-20',
    situacion: 'Publicaste una opinión sobre un tema de tu ciudad y un desconocido comentó: "Qué opinión tan estúpida, se nota que no sabes nada". Otros le dieron "me gusta". Llevas una hora escribiendo y borrando una respuesta que lo deje en ridículo, y no puedes pensar en otra cosa.',
    depende: ['Decidir si respondes y cómo', 'Bloquear o silenciar', 'Volver a tu día'],
    noDepende: ['Lo que piense un desconocido', 'Los "me gusta" de otros', 'El tono de internet'],
    respuesta: 'Epicteto: no te ofende quien te insulta, sino tu juicio de que eso es ofensivo. Un desconocido, detrás de una pantalla, que no sabe nada de ti, acaba de ocupar una hora de tu vida. ¿Vale ese precio? La respuesta ingeniosa te dará satisfacción un minuto y te meterá en una discusión que no tiene fin. Si su comentario tuviera un argumento, podrías responder al argumento. Como es solo un insulto, lo más estoico suele ser no responder: silenciar y volver a lo tuyo. Tu opinión no se volvió estúpida porque alguien lo diga. Y tu paz no debe estar disponible para cualquiera con conexión a internet.',
    pregunta: '¿A cuántos desconocidos les has dado hoy acceso a tu tranquilidad?',
  },
  {
    slug: 'vidas-perfectas', titulo: 'Las vidas perfectas de Instagram', ambito: 'redes', principio: 'los-indiferentes', virtud: 'sabiduria', cita: 'med-12-4',
    situacion: 'Es domingo por la noche y mañana madrugas. Llevas más de una hora viendo historias: viajes a Europa, cenas elegantes, cuerpos perfectos, anuncios de compromiso. Tu vida, en comparación, parece gris: trabajo, bus, casa. Cierras la aplicación sintiéndote peor que cuando la abriste.',
    depende: ['Cuánto tiempo pasas en redes', 'A quién sigues', 'Recordar que ves una selección, no la vida entera'],
    noDepende: ['Lo que otros publican', 'Cómo están diseñadas las redes', 'Las vidas de los demás'],
    respuesta: 'Estás comparando tu vida completa con los mejores momentos editados de cientos de personas. Es una comparación imposible de ganar. Marco Aurelio se asombraba de cuánto nos importa lo que otros piensan; hoy, además, nos importa lo que otros muestran. Los viajes y las cenas son indiferentes: agradables, pero no hacen buena una vida. Y detrás de cada foto hay días grises como los tuyos. Lo que depende de ti: poner un límite de tiempo, dejar de seguir cuentas que te hacen sentir menos, y seguir las que te enseñan algo. Y esta noche, en lugar de mirar vidas ajenas, haz algo pequeño que te guste de la tuya.',
    pregunta: '¿Qué cuentas que sigues te dejan peor de lo que estabas?',
  },
  {
    slug: 'pocos-likes', titulo: 'Tu publicación no tuvo "me gusta"', ambito: 'redes', principio: 'los-indiferentes', virtud: 'templanza', cita: 'enq-48',
    situacion: 'Publicaste un dibujo que hiciste con mucho cariño. Pasaron tres horas y solo tiene cuatro "me gusta". La foto del almuerzo de tu amiga tiene doscientos. Revisas la publicación cada diez minutos y empiezas a pensar en borrarla porque te da vergüenza que se vea que "a nadie le gustó".',
    depende: ['Por qué dibujas', 'Seguir dibujando', 'No medir tu trabajo por reacciones'],
    noDepende: ['El algoritmo', 'Los gustos de otros', 'Cuántas personas ven la publicación'],
    respuesta: 'Pregúntate: ¿dibujaste para que te dieran "me gusta" o porque disfrutas dibujar? Si es lo segundo, el dibujo ya cumplió su propósito antes de publicarlo. Los "me gusta" son un indiferente, y además no miden calidad: miden algoritmos, horarios y hábitos de desplazamiento. Epicteto decía que quien progresa no busca alabanzas. No borres tu dibujo; déjalo ahí, como un registro de tu camino. Y considera ocultar el contador de reacciones o publicar sin mirar durante un día. Tu trabajo vale por el cuidado que pusiste, no por el número debajo.',
    pregunta: '¿Seguirías haciendo lo que te gusta si nadie reaccionara?',
  },
  {
    slug: 'noticia-alarmante', titulo: 'Las noticias te llenan de angustia', ambito: 'redes', principio: 'dicotomia-del-control', virtud: 'sabiduria', cita: 'med-4-24',
    situacion: 'Cada mañana, antes de levantarte, lees noticias en el celular: guerras, crisis económica, crímenes, cambio climático. Te levantas con el corazón apretado y la sensación de que el mundo se derrumba. Pasas el día irritable y sin energía, pero no puedes dejar de leer.',
    depende: ['Cuándo y cuánto consumes noticias', 'Elegir fuentes serias y menos alarmistas', 'Actuar en lo que sí puedes influir'],
    noDepende: ['Lo que pasa en el mundo', 'La forma en que los medios presentan las noticias', 'La mayoría de los problemas globales'],
    respuesta: 'Informarse es bueno; ahogarse en noticias antes de levantarte, no. Marco Aurelio aconsejaba ocuparse de lo necesario. La mayoría de lo que lees cada mañana no depende de ti, y leerlo en la cama solo te llena de angustia sin darte ningún poder para actuar. Prueba esto: nada de noticias la primera hora del día. Luego, un momento fijo, quince minutos, con fuentes serias. Y pregúntate con cada tema: ¿hay algo que yo pueda hacer? Si la respuesta es sí —donar, votar, ayudar en tu barrio—, hazlo. Si es no, suéltalo. Preocuparte por todo no ayuda al mundo; actuar bien donde estás, sí.',
    pregunta: '¿Qué cosa pequeña podrías hacer hoy por el mundo, en lugar de solo preocuparte?',
  },
  {
    slug: 'grupo-familiar-whatsapp', titulo: 'El grupo familiar comparte noticias falsas', ambito: 'redes', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'med-2-1',
    situacion: 'En el grupo de WhatsApp de la familia, tu tía comparte por tercera vez esta semana una noticia falsa sobre vacunas. Otros la reenvían. Tú ya corregiste antes y te respondieron que eras un "sabelotodo". Estás a punto de escribir un mensaje largo y enojado, o de salirte del grupo.',
    depende: ['Decidir cuándo vale la pena corregir', 'Hacerlo con respeto y fuentes', 'Hablar en privado con quien comparte'],
    noDepende: ['Lo que tu familia crea', 'Que acepten tus correcciones', 'La cantidad de información falsa que circula'],
    respuesta: 'Marco Aurelio empezaba sus días recordando que encontraría gente que se equivoca, y que su tarea no era enojarse sino colaborar. Corregir desinformación es un acto de justicia, pero la forma importa. Un mensaje largo y enojado en el grupo pone a todos a la defensiva. Prueba otra vía: escríbele a tu tía en privado, con cariño: "Tía, vi lo que compartiste; yo también me preocuparía, pero encontré que no es cierto. Te paso esta fuente". Nadie cambia de opinión cuando se siente humillado en público. Y si no la convences, habrás hecho tu parte. El resto no depende de ti.',
    pregunta: '¿Estás buscando que tengan la información correcta o que admitan que tienes razón?',
  },
  {
    slug: 'ex-en-redes', titulo: 'Ves a tu ex feliz con otra persona', ambito: 'redes', principio: 'amor-fati', virtud: 'templanza', cita: 'enq-8',
    situacion: 'Seis meses después de terminar, te aparece una foto de tu ex en la playa, abrazado con su nueva pareja. Sientes un golpe en el estómago. Empiezas a revisar su perfil, el de ella, fotos viejas, y a imaginar que él está mucho mejor que tú.',
    depende: ['Dejar de mirar', 'Silenciar o dejar de seguir', 'Volver a lo que construyes hoy'],
    noDepende: ['La vida de tu ex', 'Con quién está', 'Lo que decide publicar'],
    respuesta: 'Epicteto aconseja querer que las cosas sucedan como suceden. Tu ex siguió su vida; eso ya ocurrió y no depende de ti. Lo que sí depende de ti es no hacer arqueología en sus redes, que solo reabre la herida. Una foto en la playa no te dice si él es más feliz; te dice que hubo un momento bonito que decidió mostrar. Silenciarlo no es inmadurez; es templanza, cuidar lo que dejas entrar en tu mente. Cierra la aplicación y haz algo que te conecte con tu presente: llama a un amigo, sal a caminar. Tu vida no es una competencia con la suya.',
    pregunta: '¿Qué te ayudaría más hoy: saber de su vida o cuidar la tuya?',
  },
  {
    slug: 'funa', titulo: 'Te critican públicamente en redes', ambito: 'redes', principio: 'apatheia', virtud: 'coraje', cita: 'med-4-49',
    situacion: 'Un video tuyo, sacado de contexto, se volvió viral con comentarios que te llaman grosero. Cientos de personas opinan sin conocer la situación. Recibes mensajes agresivos, y hay compañeros de trabajo que lo vieron. Sientes que tu reputación se destruyó en una tarde.',
    depende: ['No responder en caliente', 'Aclarar con serenidad si es necesario', 'Proteger tu seguridad y bienestar', 'Hablar con quienes te conocen'],
    noDepende: ['Lo que opine la gente en internet', 'La velocidad con que se difunde', 'Tu reputación entre desconocidos'],
    respuesta: 'La reputación es, según los estoicos, un indiferente: puede ser buena o mala, y no está en tus manos. Eso no hace que esto duela menos, pero sí indica dónde poner tu energía. Marco Aurelio usaba la imagen del promontorio que resiste las olas. No tienes que responder a cada comentario; no respondas en caliente. Si hubo un error de tu parte, reconócelo con sencillez. Si todo fue sacado de contexto, una aclaración breve y serena, una sola vez, basta. Habla con quienes te conocen de verdad: su opinión es más valiosa que la de miles de desconocidos. Protege tu seguridad, y si los mensajes te desbordan, busca apoyo profesional. Estas olas también pasan.',
    pregunta: '¿Quiénes te conocen de verdad, y qué pensarían de ti?',
    ayuda: true,
  },
  {
    slug: 'adiccion-al-scroll', titulo: 'Tres horas de videos sin darte cuenta', ambito: 'redes', principio: 'vivir-segun-la-naturaleza', virtud: 'templanza', cita: 'sen-brev-1',
    situacion: 'Te acostaste a las diez con la intención de dormir temprano. Abriste una aplicación de videos cortos "solo un momento". Cuando miras el reloj, es la una de la madrugada. No recuerdas casi nada de lo que viste. Te sientes vacío y un poco avergonzado.',
    depende: ['Dejar el celular fuera de la habitación', 'Usar límites de tiempo', 'Tener otra actividad para antes de dormir'],
    noDepende: ['El diseño adictivo de las aplicaciones', 'Los videos que te recomiendan', 'El tiempo que ya pasó'],
    respuesta: 'Séneca escribió que no es que tengamos poco tiempo, sino que perdemos mucho. Tres horas de videos que no recuerdas son un ejemplo perfecto. No te castigues: estas aplicaciones están diseñadas por equipos enormes para capturar tu atención. Precisamente por eso, la voluntad sola no basta; necesitas cambiar el entorno. Esta noche, deja el celular cargando fuera del cuarto y ten un libro en la mesa de noche. Pon un límite diario en la aplicación. Vivir según tu naturaleza racional incluye elegir en qué pones tu atención, en lugar de dejar que otros elijan por ti.',
    pregunta: '¿Qué harías con tres horas libres si las eligieras tú?',
  },
  {
    slug: 'discusion-politica-online', titulo: 'Te enganchaste en una discusión política', ambito: 'redes', principio: 'dicotomia-del-control', virtud: 'sabiduria', cita: 'med-11-18',
    situacion: 'Llevas dos horas discutiendo en los comentarios de una publicación política con alguien que no conoces. Cada respuesta suya te parece más absurda y cada respuesta tuya es más larga. Tu cena se enfrió y tienes el corazón acelerado. Ninguno de los dos va a cambiar de opinión.',
    depende: ['Salir de la discusión', 'Elegir espacios donde dialogar tenga sentido', 'Actuar políticamente de formas concretas'],
    noDepende: ['Lo que piense esa persona', 'Ganar la discusión', 'El tono de las redes sociales'],
    respuesta: 'Marco Aurelio anotó que las consecuencias de la ira son más graves que las causas que la provocan. Ahora mismo tu cena está fría, tu noche arruinada y tu corazón acelerado, y el mundo sigue exactamente igual. Discutir con un desconocido en comentarios casi nunca cambia opiniones; suele endurecerlas. Si te importa la política, hay acciones que sí dependen de ti: informarte bien, votar, participar en tu comunidad, conversar cara a cara con respeto. Escribe "entiendo tu punto, pienso distinto, que estés bien", y cierra la aplicación. No es rendirse: es elegir dónde pones tu energía.',
    pregunta: '¿Qué acción política concreta, fuera de las redes, podrías hacer este mes?',
  },
  {
    slug: 'mensaje-sin-responder-grupo', titulo: 'Te dejaron fuera de un grupo de chat', ambito: 'redes', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'enq-43',
    situacion: 'Descubres que tus compañeros de trabajo crearon un grupo de chat nuevo para organizar salidas y no te incluyeron. Te enteras porque alguien lo mencionó frente a ti y luego cambió de tema. Te sientes excluido y empiezas a actuar distante con todos.',
    depende: ['Preguntar con naturalidad', 'No castigar a todos por la situación', 'Construir relaciones de a uno'],
    noDepende: ['Quién crea grupos y a quién invita', 'Las razones que tuvieron', 'Lo que piensen de ti'],
    respuesta: 'Epicteto enseña a buscar el asa por donde las cosas se pueden llevar. Por un asa, esto es "me excluyeron a propósito". Por otra, "es un grupo que armaron algunos, quizá sin pensarlo mucho". No sabes cuál es la verdad. Lo que sí sabes es que tu distancia con todos está castigando incluso a quienes no tuvieron nada que ver. Puedes preguntar con naturalidad: "Oí que organizan salidas; me gustaría sumarme alguna vez". Si te incluyen, bien. Si no, puedes construir relaciones de otra manera: invitar tú a un café a alguien del equipo. La pertenencia también se construye, no solo se recibe.',
    pregunta: '¿A quién podrías invitar tú, en lugar de esperar que te inviten?',
  },
];
