export default [
  {
    slug: 'diagnostico-cronico', titulo: 'Un diagnóstico que cambia tu rutina', ambito: 'salud', principio: 'amor-fati', virtud: 'coraje', cita: 'dis-1-1',
    situacion: 'El médico te confirma que tienes diabetes tipo 2. Tendrás que cambiar tu alimentación, hacer ejercicio y tomar medicamentos. Sales de la consulta con rabia: te gustaba comer lo que querías, y sientes que tu vida acaba de volverse una lista de prohibiciones. Esa noche pides una hamburguesa "por última vez".',
    depende: ['Seguir el tratamiento', 'Aprender sobre tu condición', 'Buscar comidas saludables que disfrutes', 'Pedir apoyo a tu familia'],
    noDepende: ['El diagnóstico', 'Tu herencia genética', 'Lo que ya comiste en el pasado'],
    respuesta: 'Epicteto tiene una pregunta que sirve aquí: tengo que pasar por esto, ¿tengo que pasarlo además lamentándome? El diagnóstico no depende de ti; la actitud con que lo asumes, sí. La hamburguesa de "última vez" es un pequeño duelo, y está bien. Pero luego viene la tarea: aprender, experimentar con comidas nuevas, moverte cada día un poco. La templanza que ahora necesitas no es un castigo; es una forma de cuidar lo que tienes. Muchos descubren con un diagnóstico así que pueden disfrutar más con menos. Tu cuerpo no te traicionó; te está pidiendo que lo escuches. Sigue las indicaciones médicas: el estoicismo acompaña, no reemplaza al médico.',
    pregunta: '¿Qué pequeño hábito saludable podrías empezar a disfrutar esta semana?',
  },
  {
    slug: 'espera-de-resultados', titulo: 'Esperando los resultados de una biopsia', ambito: 'salud', principio: 'premeditatio-malorum', virtud: 'coraje', cita: 'med-7-8',
    situacion: 'Te hicieron una biopsia de un nódulo y los resultados llegan en diez días. El médico dijo que "probablemente no es nada", pero tú pasas las noches buscando en internet, leyendo historias de otros y ensayando mentalmente cómo darías una mala noticia a tu familia.',
    depende: ['Limitar las búsquedas en internet', 'Llenar estos días con rutinas que te sostengan', 'Hablar con alguien de confianza sobre tu miedo'],
    noDepende: ['El resultado', 'El tiempo que tarde el laboratorio', 'Lo que le haya pasado a otros'],
    respuesta: 'Marco Aurelio escribió que no te inquiete el futuro: llegarás a él, si es preciso, con la misma razón que hoy usas para el presente. El resultado todavía no existe para ti; lo que existe son estos diez días, y los estás viviendo como si ya hubiera llegado lo peor. Buscar en internet no te prepara, te asusta. Si quieres prepararte, hazlo una sola vez, brevemente: "Si es malo, lo enfrentaré con los médicos y con los míos". Luego vuelve al día: trabaja, camina, cocina, llama a alguien. Si el miedo es muy intenso, dilo. Hablarlo no lo hace real; lo hace compartido.',
    pregunta: '¿Qué harías hoy si decidieras vivir estos días en lugar de solo esperarlos?',
  },
  {
    slug: 'dolor-cronico', titulo: 'El dolor de espalda no se va', ambito: 'salud', principio: 'apatheia', virtud: 'templanza', cita: 'med-4-7',
    situacion: 'Hace meses tienes dolor de espalda. Fuiste al médico, haces terapia, pero hay días en que te cuesta levantarte. Estás irritable con todos y sientes que el dolor te quitó tu vida anterior. Cada mañana piensas: "otra vez, esto nunca va a mejorar".',
    depende: ['Seguir el tratamiento con constancia', 'Adaptar tus actividades en lugar de abandonarlas', 'Cómo le hablas a tu dolor y a los demás'],
    noDepende: ['La intensidad del dolor cada día', 'El ritmo de la recuperación', 'Que el dolor desaparezca del todo'],
    respuesta: 'El dolor físico es real y no se discute. Pero los estoicos observaban que al dolor solemos añadirle un segundo peso: "nunca va a mejorar", "mi vida está arruinada". Marco Aurelio, que sufría problemas de salud, escribió: suprime el juicio "me han dañado" y queda suprimido el daño. No elimina el dolor, pero sí el sufrimiento extra. Prueba a describirlo sin adjetivos: "hoy me duele la zona lumbar, intensidad seis". Eso es distinto a "esto es insoportable". Sigue tu tratamiento, ajusta lo que haces sin renunciar a todo. Y cuida cómo tratas a los demás: el dolor no es culpa suya.',
    pregunta: '¿Qué frase le añades a tu dolor que lo hace más pesado?',
  },
  {
    slug: 'duelo-reciente', titulo: 'Murió alguien que amabas', ambito: 'salud', principio: 'amor-fati', virtud: 'templanza', cita: 'enq-11',
    situacion: 'Hace tres semanas murió tu padre, de forma repentina. Volviste al trabajo y todos esperan que funciones con normalidad. Tú sientes un vacío enorme; hay mañanas en que no puedes levantarte. Alguien te dijo que "los estoicos no lloran", y te sientes débil por no poder con esto.',
    depende: ['Permitirte llorar y sentir', 'Pedir tiempo y apoyo', 'Buscar acompañamiento profesional si lo necesitas', 'Honrar su memoria a tu manera'],
    noDepende: ['Su muerte', 'El tiempo que dure el duelo', 'Lo que otros esperen de ti'],
    respuesta: 'Quien te dijo que los estoicos no lloran se equivoca. Séneca escribió cartas de consuelo donde admite que las lágrimas son naturales y que lo que él criticaba era el llanto fingido o sin fin, no el dolor sincero. El duelo no es debilidad; es el precio del amor. Epicteto hablaba de "devolver" lo que amamos: no para dejar de sentir, sino para agradecer lo que se tuvo. Hoy lo que depende de ti es muy poco, y está bien: comer algo, dormir, dejarte acompañar. Pide tiempo en el trabajo si puedes. Si el vacío te impide funcionar por mucho tiempo o aparecen pensamientos de no querer vivir, busca ayuda profesional de inmediato. No tienes que atravesar esto solo.',
    pregunta: '¿Quién podría acompañarte hoy, aunque sea un rato?',
    ayuda: true,
  },
  {
    slug: 'insomnio', titulo: 'No puedes dormir pensando en todo', ambito: 'salud', principio: 'dicotomia-del-control', virtud: 'templanza', cita: 'med-4-3',
    situacion: 'Son las tres de la madrugada. Llevas dos horas dando vueltas: la reunión de mañana, una conversación pendiente, el pago de la tarjeta. Cuanto más intentas dormir, más despierto estás. Miras el reloj cada quince minutos, calculando cuántas horas te quedan.',
    depende: ['Anotar los pendientes para sacarlos de la cabeza', 'Levantarte un rato si no duermes', 'Cuidar tus hábitos de sueño durante el día'],
    noDepende: ['Quedarte dormido a voluntad', 'Los problemas que te esperan mañana', 'La hora que marca el reloj'],
    respuesta: 'Dormir no se puede forzar; es una de las cosas que no dependen de tu voluntad directa. Por eso, luchar contra el insomnio lo empeora. Lo que sí depende de ti es dejar de pelear. Enciende una luz tenue, anota cada preocupación en una hoja con su primer paso para mañana y dile a tu mente: "Ya está anotado; lo atiendo mañana". Marco Aurelio hablaba de retirarse a la propia alma como a un refugio tranquilo. Respira lento, sin exigir dormir: descansar ya es bueno. Y voltea el reloj: contar horas solo alimenta la angustia. Si el insomnio se repite muchas semanas, consúltalo con un médico.',
    pregunta: '¿Qué pensamiento podrías dejar en papel esta noche para no llevarlo a la cama?',
  },
  {
    slug: 'cuerpo-en-el-espejo', titulo: 'No te gusta lo que ves en el espejo', ambito: 'salud', principio: 'los-indiferentes', virtud: 'sabiduria', cita: 'med-5-16',
    situacion: 'Te pruebas el vestido para el matrimonio de tu prima y no cierra. Te miras en el espejo y empiezas a criticarte: la barriga, los brazos, la cara. Decides no ir a la fiesta y empezar mañana una dieta extrema que viste en redes.',
    depende: ['Cómo te hablas a ti misma', 'Cuidar tu salud con hábitos sostenibles', 'Buscar ropa que te quede hoy'],
    noDepende: ['Los estándares de belleza', 'Lo que otros opinen de tu cuerpo', 'Los cambios de tu cuerpo con el tiempo'],
    respuesta: 'La apariencia es un indiferente: no te hace mejor ni peor persona. Pero la forma en que te hablas frente al espejo no es indiferente; Marco Aurelio decía que el alma se tiñe del color de sus pensamientos. Si repites cada día "qué horror", tu ánimo tomará ese color. Prueba a hablarte como hablarías a una amiga querida. Cuidar tu cuerpo es bueno, pero desde el respeto, no desde el castigo: las dietas extremas suelen terminar en rebote y culpa. Si quieres cambiar hábitos, consulta a un profesional. Y ve a la fiesta: busca un vestido que te quede hoy. Tu prima quiere tu presencia, no una talla.',
    pregunta: '¿Le hablarías a alguien que quieres como te hablaste frente al espejo?',
  },
  {
    slug: 'ansiedad-antes-de-hablar', titulo: 'El pánico antes de hablar en público', ambito: 'salud', principio: 'apatheia', virtud: 'coraje', cita: 'sen-ira-2-3',
    situacion: 'Mañana tienes que presentar tu proyecto ante veinte personas, entre ellas la directora del área. Solo pensarlo te acelera el corazón, te sudan las manos y sientes que se te va a olvidar todo. Estás considerando inventar que estás enfermo para no ir.',
    depende: ['Prepararte y ensayar', 'Aceptar los nervios sin pelear con ellos', 'Enfocarte en el mensaje, no en tu imagen'],
    noDepende: ['Tus reacciones físicas automáticas', 'Lo que piense cada persona del público', 'Que todo salga perfecto'],
    respuesta: 'Séneca explicaba que los primeros movimientos del cuerpo —el corazón acelerado, las manos frías— no dependen de nuestra voluntad. Les pasan también a los más serenos. El error es interpretarlos como "voy a fracasar". Son solo energía preparándote para algo que te importa. Lo que depende de ti: ensayar en voz alta tres veces, preparar notas claras, respirar lento antes de empezar. Y cambiar el foco: no se trata de que te admiren, sino de que entiendan tu proyecto. Tu imagen no es tuya; tu mensaje, sí. El coraje no es no sentir miedo; es presentarse con él. Y si la ansiedad te limita con frecuencia, un profesional puede ayudarte.',
    pregunta: '¿Qué pasaría si trataras a tus nervios como un aliado en lugar de un enemigo?',
  },
  {
    slug: 'dejar-de-fumar', titulo: 'Quieres dejar de fumar y recaíste', ambito: 'salud', principio: 'vivir-segun-la-naturaleza', virtud: 'templanza', cita: 'dis-2-18',
    situacion: 'Llevabas veintidós días sin fumar. Ayer, después de una discusión, compraste una cajetilla y te fumaste cuatro cigarrillos. Hoy te sientes un fracaso total y piensas que ya da igual, que mejor sigues fumando porque "no tienes fuerza de voluntad".',
    depende: ['Volver a empezar hoy', 'Identificar el detonante', 'Preparar una alternativa para la próxima discusión', 'Pedir apoyo'],
    noDepende: ['La recaída de ayer', 'Las ganas que aparecen solas', 'Las discusiones que ocurran'],
    respuesta: 'Epicteto enseñaba que los hábitos se fortalecen con las acciones que les corresponden y se debilitan cuando dejas de alimentarlos. Veintidós días no se borran por un mal día: fortalecieron tu capacidad. Pensar "ya da igual" es un juicio falso que te empuja a abandonar. La verdad es que recaer es parte de casi todos los procesos de cambio. Lo que depende de ti es hoy. Mira el detonante: una discusión. Prepara qué harás la próxima vez: caminar, respirar, llamar a alguien. Y cuenta de nuevo desde uno, sin castigo. Un profesional de salud puede ayudarte con estrategias y apoyo.',
    pregunta: '¿Qué harás distinto la próxima vez que aparezca el detonante?',
  },
  {
    slug: 'cansancio-cuidador', titulo: 'Estás agotado y no puedes parar', ambito: 'salud', principio: 'vivir-segun-la-naturaleza', virtud: 'sabiduria', cita: 'med-4-24',
    situacion: 'Trabajas, estudias de noche y los fines de semana ayudas en el negocio familiar. Hace semanas duermes cinco horas. Tienes dolores de cabeza frecuentes, olvidas cosas y te irritas con todo. Crees que descansar es de flojos y que ya descansarás cuando termines la carrera.',
    depende: ['Revisar tus compromisos', 'Pedir ayuda o reducir algo', 'Proteger unas horas mínimas de sueño'],
    noDepende: ['Las horas que tiene el día', 'Los límites de tu cuerpo', 'Lo que otros piensen si bajas el ritmo'],
    respuesta: 'Vivir según la naturaleza incluye respetar la tuya: eres un ser humano con un cuerpo que necesita descanso. Ignorarlo no es disciplina, es falta de sabiduría. Marco Aurelio aconsejaba ocuparse de lo necesario y quitar lo superfluo. Haz una lista de todos tus compromisos. ¿Cuáles son imprescindibles? ¿Cuáles podrías delegar, reducir o posponer? El descanso no es flojera; es parte del trabajo bien hecho. Un cuerpo agotado toma malas decisiones y trata peor a los demás. Si los dolores de cabeza y el cansancio persisten, consulta a un médico. Y duerme esta noche siete horas: considéralo tu tarea más importante.',
    pregunta: '¿Qué compromiso podrías soltar esta semana sin que el mundo se derrumbe?',
  },
  {
    slug: 'envejecer', titulo: 'Te cuesta aceptar que envejeces', ambito: 'salud', principio: 'amor-fati', virtud: 'sabiduria', cita: 'med-4-23',
    situacion: 'Cumples sesenta años. Te cuesta subir escaleras que antes subías corriendo, necesitas lentes para todo y en el trabajo te tratan con una consideración que te hace sentir viejo. Esta mañana te dijiste que "lo mejor ya pasó" y el día se te hizo gris.',
    depende: ['Cuidar tu salud a esta edad', 'Aprender cosas nuevas', 'Compartir lo que sabes', 'Cómo interpretas esta etapa'],
    noDepende: ['El paso del tiempo', 'Los cambios de tu cuerpo', 'Cómo te perciben los demás'],
    respuesta: 'Marco Aurelio escribió su diario ya mayor, cansado y enfermo, y allí dice: nada de lo que llega a su tiempo es prematuro ni tardío. Envejecer es una estación, no una derrota. "Lo mejor ya pasó" es un juicio, y puedes ponerlo en duda: ¿qué tienes hoy que no tenías a los treinta? Quizá paciencia, perspectiva, menos necesidad de aprobación. Séneca decía que la vejez está llena de placeres si se sabe usarla. Cuida tu cuerpo con lo que está a tu alcance: caminar, comer bien, consultar al médico. Y busca algo que aprender o enseñar. Todavía hay mucho camino, solo que a otro paso.',
    pregunta: '¿Qué sabe tu yo de hoy que tu yo de treinta años necesitaba saber?',
  },
];
