export default [
  {
    slug: 'correo-del-jefe', titulo: 'El correo seco del jefe', ambito: 'trabajo', principio: 'apatheia', virtud: 'sabiduria', cita: 'enq-5',
    situacion: 'Son las 9:40 de la noche y te llega un correo de tu jefa: "Necesito hablar contigo mañana a primera hora sobre el informe". Nada más. Sin saludo, sin contexto. Empiezas a imaginar que el informe estaba mal, que vas a quedar como incompetente, que quizá hasta peligra tu puesto. Ya no puedes dormir.',
    depende: ['Cómo interpretas un mensaje ambiguo', 'Repasar el informe diez minutos y cerrar el computador', 'Llegar descansado y escuchar antes de defenderte'],
    noDepende: ['Lo que tu jefa quiere decirte', 'El tono con que escribe sus correos', 'La decisión que tome sobre el informe'],
    respuesta: 'El correo tiene diecisiete palabras; la historia de tu despido la escribiste tú. Epicteto diría que no te perturba el mensaje sino tu juicio sobre él. Nota la diferencia entre el hecho ("quiere hablar sobre el informe") y el añadido ("está furiosa y me va a echar"). El añadido no tiene pruebas. Haz lo que depende de ti esta noche: revisa el informe si te da paz, anota dos o tres puntos que quieras explicar y luego suelta. Mañana escucharás primero. Si hay errores, los reconocerás y propondrás cómo corregirlos; eso también es tuyo. El resto —su humor, su decisión— nunca estuvo en tus manos, ni esta noche ni mañana.',
    pregunta: '¿Qué parte de tu preocupación es hecho y qué parte es historia que tú añadiste?',
  },
  {
    slug: 'credito-robado', titulo: 'Alguien presentó tu idea como suya', ambito: 'trabajo', principio: 'dicotomia-del-control', virtud: 'justicia', cita: 'med-6-6',
    situacion: 'En la reunión mensual, un compañero presenta la propuesta de automatizar los reportes. Es exactamente lo que tú le comentaste en el almuerzo la semana pasada. El gerente lo felicita frente a todos. Tú sientes calor en la cara y ganas de interrumpir para decir "eso fue idea mía", pero te quedas callado y sales de la reunión con rabia.',
    depende: ['Hablar con tu compañero en privado, sin acusar', 'Documentar tus ideas y compartirlas por escrito', 'No devolver la jugada con otra igual'],
    noDepende: ['Lo que tu compañero hizo', 'Lo que el gerente cree ahora', 'Que otros reconozcan tu aporte'],
    respuesta: 'La rabia es comprensible: hubo una injusticia. Pero fíjate en qué quiere la rabia: venganza, humillarlo en público, que todos sepan. Nada de eso está en tu mano, y perseguirlo te volvería parecido a él. Marco Aurelio decía que la mejor defensa es no parecerse a quien te ofende. Lo que sí es tuyo es la justicia bien entendida: hablar con él, en privado y con calma: "Me sorprendió ver mi idea presentada sin mencionarme; para la próxima prefiero que la trabajemos juntos". Y, de aquí en adelante, compartir tus propuestas por escrito. No controlas el reconocimiento ajeno. Sí controlas seguir siendo alguien que aporta ideas, aunque a veces otros se las lleven.',
    pregunta: '¿Qué quieres realmente: reconocimiento o seguir siendo alguien íntegro? ¿Cómo sería actuar desde lo segundo?',
  },
  {
    slug: 'despido-por-reestructuracion', titulo: 'Te despiden por reestructuración', ambito: 'trabajo', principio: 'amor-fati', virtud: 'coraje', cita: 'med-5-20',
    situacion: 'Después de seis años en la empresa, un viernes te llaman a Recursos Humanos. La compañía se fusiona y tu cargo desaparece. Te entregan una carta, te agradecen y te piden devolver el computador. Sales a la calle con una caja en las manos, pensando en el arriendo, en tu familia y en que a tu edad "ya nadie contrata".',
    depende: ['Darte unos días para sentir el golpe sin castigarte', 'Revisar tus finanzas y hacer un plan de tres meses', 'Contactar a tu red con honestidad', 'Actualizar tu hoja de vida'],
    noDepende: ['La decisión de la fusión', 'El mercado laboral de este mes', 'Lo que otros piensen de tu salida'],
    respuesta: 'Duele, y está bien que duela: los estoicos no piden sonreír ante una pérdida. Pero sí distinguen el golpe del relato. El golpe es real: menos ingresos, incertidumbre. El relato ("ya nadie me va a contratar", "fracasé") es un juicio que puedes revisar. Tu trabajo no era tuyo; era prestado, como dice Epicteto de todo lo externo. Tu competencia, tu disciplina y tu forma de tratar a la gente sí lo son, y salen contigo por la puerta. Marco Aurelio escribió que lo que se interpone en el camino se convierte en el camino. Esta semana el camino es concreto: números, llamadas, una lista de posibilidades. Un paso cada día. El coraje no es no tener miedo; es hacer la llamada con miedo.',
    pregunta: '¿Qué te llevas contigo de estos años que nadie te puede quitar?',
  },
  {
    slug: 'companero-que-no-aporta', titulo: 'El compañero que no hace su parte', ambito: 'trabajo', principio: 'cosmopolitismo', virtud: 'justicia', cita: 'med-2-1',
    situacion: 'En el proyecto en equipo, uno de tus compañeros entrega tarde, responde con evasivas y ayer dijo en el chat del grupo que "ya casi terminaba", aunque no ha subido nada. La entrega es el lunes. Tú ya has cubierto parte de su trabajo dos veces y sientes que eres el único adulto del equipo.',
    depende: ['Hablar claro con él sobre fechas y consecuencias', 'Informar al líder si la entrega corre riesgo', 'Poner un límite a cuánto trabajo ajeno asumes'],
    noDepende: ['Su nivel de compromiso', 'Las razones que tenga (que quizá desconoces)', 'Que cambie su forma de trabajar'],
    respuesta: 'Marco Aurelio se preparaba cada mañana para encontrarse con personas perezosas o ingratas, y añadía: han nacido, como yo, para colaborar. Eso no significa aguantarlo todo; significa no convertir a tu compañero en un enemigo. Quizá está pasando algo que no sabes. Pregúntale directamente: "¿Qué te está pasando con esta parte? Necesito saber para el viernes si la vas a entregar". Si no responde, informa al líder con hechos, no con adjetivos. Eso es justicia hacia el equipo. Lo que no es justicia es cargar con todo en silencio y acumular resentimiento: eso tampoco le sirve a la colmena. Tu parte es actuar con claridad y buena fe; su respuesta es asunto suyo.',
    pregunta: '¿Qué conversación clara estás evitando por miedo a parecer duro?',
  },
  {
    slug: 'critica-en-evaluacion', titulo: 'Una crítica dura en tu evaluación', ambito: 'trabajo', principio: 'apatheia', virtud: 'sabiduria', cita: 'dis-2-17',
    situacion: 'En la evaluación anual tu jefe te dice que "te falta liderazgo" y que en las reuniones "no se te siente". Tú crees que has trabajado más que nunca. Sales ofendido, repasando mentalmente todo lo que hiciste y todos los errores de él, y pasas la tarde contándole a un amigo lo injusto que fue.',
    depende: ['Separar la crítica útil del tono con que llegó', 'Pedir ejemplos concretos', 'Decidir qué vas a practicar'],
    noDepende: ['La opinión de tu jefe', 'Cómo formula sus críticas', 'La calificación ya registrada'],
    respuesta: 'La ofensa inmediata es un primer movimiento; no lo elegiste. Lo que haces después, sí. Epicteto advierte que nadie aprende lo que cree que ya sabe. Antes de defenderte, pregúntate con honestidad: ¿hay algo de verdad en lo que dijo? Quizá trabajas mucho pero en silencio, y eso otros no lo ven. Pide ejemplos concretos: "¿En qué reunión habrías esperado que hablara?". Si la crítica tiene fundamento, es un regalo incómodo; si no lo tiene, no te quita nada, porque tu valor no depende de su opinión. En ambos casos, la pregunta útil no es "¿quién tiene razón?" sino "¿qué puedo practicar desde mañana?".',
    pregunta: 'Si esa crítica fuera un veinte por ciento cierta, ¿cuál sería ese veinte por ciento?',
  },
  {
    slug: 'sobrecarga', titulo: 'Te piden un proyecto más', ambito: 'trabajo', principio: 'los-indiferentes', virtud: 'templanza', cita: 'med-4-24',
    situacion: 'Ya trabajas hasta las siete casi todos los días y los fines de semana revisas el correo. Hoy tu gerente te pide liderar un proyecto nuevo "porque eres el más confiable". Te halaga, podría ayudarte a un ascenso, pero sabes que tu salud y tu familia ya están pagando el precio de tu agenda.',
    depende: ['Responder con honestidad sobre tu capacidad', 'Proponer qué dejarías de hacer para asumirlo', 'Proteger ciertos límites de tiempo'],
    noDepende: ['Lo que el gerente piense si dices que no', 'Si llega o no el ascenso', 'La cantidad de trabajo que tiene la empresa'],
    respuesta: 'El ascenso y el reconocimiento son indiferentes preferibles: es razonable quererlos. Tu salud también lo es. Y tu presencia con tu familia pertenece además a la justicia: son deberes. Marco Aurelio citaba a Demócrito —ocúpate de pocas cosas si quieres estar tranquilo— y lo corregía: ocúpate de lo necesario. Decir sí a todo no es virtud; es falta de medida. Puedes responder: "Me interesa, y para hacerlo bien necesito dejar el proyecto X o recibir apoyo en Y". Eso es templanza con coraje. Si la respuesta es que debes cargar con todo, ya sabrás algo importante sobre ese lugar. Tú eliges con qué criterio decides; el resultado no es tuyo.',
    pregunta: '¿A qué estás diciendo "no" cada vez que dices "sí" a más trabajo?',
  },
  {
    slug: 'error-en-produccion', titulo: 'Tu error costó dinero a la empresa', ambito: 'trabajo', principio: 'vivir-segun-la-naturaleza', virtud: 'coraje', cita: 'med-10-16',
    situacion: 'Configuraste mal un descuento en la tienda en línea y durante cuatro horas se vendieron productos a pérdida. Nadie sabe todavía que fuiste tú; el sistema no deja registro claro. Podrías decir que fue una falla técnica. Tu estómago está hecho un nudo mientras el equipo busca al responsable.',
    depende: ['Decir la verdad', 'Proponer cómo evitar que se repita', 'Cómo te tratas a ti mismo después del error'],
    noDepende: ['Las pérdidas que ya ocurrieron', 'La reacción de tu jefe', 'Las consecuencias que decida la empresa'],
    respuesta: 'Hay un camino fácil y un camino recto, y ya sabes cuál es cuál. Marco Aurelio se reprochaba discutir demasiado sobre cómo debe ser un hombre bueno: basta con serlo. Decir "fui yo, esto pasó, así propongo evitarlo" es un acto de coraje y de justicia a la vez: evita que culpen a otros y le devuelve al equipo tiempo y confianza. Las consecuencias no dependen de ti; tu integridad, sí. Y una vez dicho, no te castigues de más: el error ya fue, y la culpa que no sirve para corregir no es virtud, es otro peso inútil. Lo que queda es aprender y seguir.',
    pregunta: '¿Qué versión de ti quieres recordar dentro de cinco años cuando pienses en este día?',
  },
  {
    slug: 'cliente-grosero', titulo: 'Un cliente te grita por teléfono', ambito: 'trabajo', principio: 'apatheia', virtud: 'templanza', cita: 'med-4-49',
    situacion: 'Trabajas en atención al cliente. Un hombre llama furioso porque su pedido no llegó; te insulta, dice que eres un inútil y que va a pedir que te despidan. Tú no manejas la logística ni tienes la culpa del retraso. Llevas seis horas de turno y sientes que se te acaba la paciencia.',
    depende: ['El tono de tu voz', 'Ofrecer la solución que sí está a tu alcance', 'Poner un límite respetuoso ante los insultos', 'Respirar antes de la siguiente llamada'],
    noDepende: ['Su enojo', 'El retraso del pedido', 'Las palabras que él elige'],
    respuesta: 'Marco Aurelio usa la imagen del promontorio: las olas rompen contra él una y otra vez, y a su alrededor el agua se calma. El insulto es una ola; no tienes que convertirte en ola. Recuerda que su rabia es con la situación, no contigo, aunque vaya dirigida a tu nombre. Epicteto diría que la ofensa solo se completa si tú aceptas el juicio "me ha humillado". Puedes responder con firmeza y calma: "Entiendo su molestia. Voy a ayudarle, y para eso necesito que hablemos con respeto". Después de colgar, tómate treinta segundos. No por él: por la siguiente persona, que merece que la atiendas limpio.',
    pregunta: '¿Qué frase podrías tener lista para cuando alguien descargue su rabia contigo?',
  },
  {
    slug: 'ascenso-a-otro', titulo: 'El ascenso se lo dieron a otra persona', ambito: 'trabajo', principio: 'los-indiferentes', virtud: 'sabiduria', cita: 'med-12-4',
    situacion: 'Durante un año te preparaste para la coordinación del área: cursos, horas extra, resultados. Hoy anunciaron que la ocupará una compañera con menos antigüedad. Todos te miran esperando tu reacción. Tú sonríes, felicitas, y por dentro sientes una mezcla de humillación y envidia que te avergüenza.',
    depende: ['Felicitarla con sinceridad', 'Pedir retroalimentación sobre la decisión', 'Revisar si ese cargo era realmente lo que querías'],
    noDepende: ['La decisión tomada', 'Lo que tus compañeros piensen de ti', 'Los criterios de quienes decidieron'],
    respuesta: 'Marco Aurelio notaba algo curioso: nos amamos más que a nadie y, sin embargo, valoramos más la opinión ajena que la nuestra. Buena parte de la humillación que sientes viene de imaginar cómo te ven. Pero el cargo era un indiferente preferible: estaba bien desearlo, y no define lo que vales. Lo que hiciste este año —aprender, trabajar bien— sigue siendo tuyo. La envidia no es un crimen; es una señal de que algo te importaba. Úsala para preguntar, sin reproche, qué pesó en la decisión. Y trata a tu nueva coordinadora como te gustaría que te hubieran tratado a ti en su lugar. Eso sí depende de ti.',
    pregunta: '¿Qué ganaste este año que no aparece en ningún organigrama?',
  },
  {
    slug: 'domingo-en-la-noche', titulo: 'La angustia del domingo en la noche', ambito: 'trabajo', principio: 'premeditatio-malorum', virtud: 'coraje', cita: 'sen-ep-13',
    situacion: 'Cada domingo, hacia las seis de la tarde, te cae encima un peso. Piensas en la semana: la reunión del lunes, los pendientes, el jefe exigente. Arruinas la última parte del fin de semana anticipando todo lo que puede salir mal, pero sin hacer nada concreto al respecto.',
    depende: ['Convertir la preocupación en una lista con primeros pasos', 'Elegir un momento breve para prepararte y luego cerrar', 'Hacer algo que disfrutes el domingo en la noche'],
    noDepende: ['Lo que ocurra realmente el lunes', 'El carácter de tu jefe', 'La cantidad de pendientes que llegan'],
    respuesta: 'Séneca lo dijo hace dos mil años: sufrimos más en la imaginación que en la realidad. La preocupación del domingo da vueltas sin salida. La premeditación estoica es distinta: tiene hora, tiene fin y termina en un plan. Prueba esto: el domingo a las cinco, quince minutos con papel. ¿Qué podría complicarse esta semana? ¿Qué haría yo si pasa? ¿Cuál es el primer paso del lunes? Escribe, cierra la libreta y sal a caminar o cocina algo. Si la angustia vuelve, dile: "Ya te atendí; te veo el lunes". Y observa el viernes cuántas de esas catástrofes ocurrieron de verdad.',
    pregunta: '¿Cuántas de las cosas que temiste el domingo pasado ocurrieron realmente?',
  },
];
